### ISSUE TITLE
[Question] How cell names are determined?

### ISSUE THREAD

**Issue by Puriney** [hms-dbmi/dropEst#10]
Here is an example of cell names present in the generated count matrix: `TGACAATACTTGATTAGAC`. 

- I would assume it is`TGACAATACTT|GATTAGAC` where the last 8 letters come from barcode-2 with fixed length and the rest comes from barcode-1 with variable length. Is it correct?
- Do you reverse transcribe barcode-1/barcode-2 to determine cell names?

I am using indrop_v2 with two cell barcodes list. One for BC-1 and the other for BC-2.

Thanks.

**Comment by VPetukhov** [comment]
> I would assume it isTGACAATACTT|GATTAGAC where the last 8 letters come from barcode-2 with fixed length and the rest comes from barcode-1 with variable length. Is it correct?

Yes, you're right.

> Do you reverse transcribe barcode-1/barcode-2 to determine cell names?

In the output, cell barcodes are the same as in the reads data, i.e. reverse-compliment according to the real barcodes. Input file with barcodes (which should be specified in the config file) must contain real barcodes without reverse transcription.

**Comment by Puriney** [comment]
Thanks for the reply.
