### ISSUE TITLE
Barcodes file in XML

### ISSUE THREAD

**Issue by aelias1** [hms-dbmi/dropEst#102]
Where can I find the 10x_aug_2016_split</barcodes_file> and what format should it be in? Thank you

**Comment by VPetukhov** [comment]
All barcodes are in [dropEst/data/barcodes/](https://github.com/hms-dbmi/dropEst/tree/master/data/barcodes). If you have combinatorial barcodes, each line in the file is a different part of reverse-compliment barcode sequence.
