### ISSUE TITLE
filtered cells are empty about indrop v2

### ISSUE THREAD

**Issue by zoe106** [hms-dbmi/dropEst#106]
Hello,

Great thank for developing this amazing tools.
I tried to use dropEst 0.8.6 to estimate the processed BAM files (after dropTag and alignment steps, and both were executed properly based on the stats). And for the dropEst step, it works fine in other projects, but failed in all samples of project PRJNA474382. The command I use is

dropest -m -L eEBA \
-g Homo_sapiens.GRCh38.99.gtf \
-c dropEst/configs/indrop_v1_2.xml \
-r ../01_dropTag/SRS1597829_gene.fastq.tagged.params.gz \
-o ../03_dropEst/SRS1597829_cell.counts.rds \
../02_alignment/SRS1597829.Aligned.sortedByCoord.out.bam

Taking SRS1597829 as a sample, there are 0 genes, 0 cells, the detail log file and the corresponding bam file are as followed. 
[est_main.log](https://github.com/hms-dbmi/dropEst/files/4597587/est_main.log)

[SRS3369198.Aligned.sortedByCoord.out.sam.txt](https://github.com/hms-dbmi/dropEst/files/4597588/SRS3369198.Aligned.sortedByCoord.out.sam.txt)

0 cells processed. Merged 0 UMIs from 0 cells.
UMI merge finished: 13:50:49.
0 cells are considered as real.
0 CBs with more than 100 genes, which have UMIs of the requested type.
no valid CBs found
Done: 13:54:17.
WARNING: filtered cells are empty. Probably, filtration threshold is too strict or you forgot to run 'merge_and_filter'

So, I was wondering how to change the cutoff of filtered cell, or merge_and_filter ?  I only find 'maximal number of output cells' and 'minimal number of genes in output cells' in the the parameter of dropEst, but it seems can't solve this problem.

Thank you!

Sincerely,
Zoe

**Comment by IOB-Muenster** [comment]
Hi Zoe,
I have the same result : 0 cells. Have you solved your problem?:)

Cheers,
Vika

**Comment by VPetukhov** [comment]
Hi,
Do you have the whitelist of barcodes for your protocol? That's the most probable reason for this error. If it's different from the one, published by the Klein lab, you need to change it in the config.

**Comment by evanbiederstedt** [comment]
There's been no update here. Feel free to update with details so we can fix things.
