### ISSUE TITLE
Droptag indrops v3

### ISSUE THREAD

**Issue by kaplinserm** [hms-dbmi/dropEst#107]
Hello,

I can't find a way to make the droptag function work on my 4 indrops files.

I use these two commands : 

declare -A library_tag=( ["primary_d20_1"]="CTCAAGAG" ["primary_d20_2"]="ATCACCTT" ["secondary_10_1"]="TAGATCTC" ["secondary_10_2"]="TCGCATAA" )

droptag -p 8 -c /home/he/dropEst/configs/indrop_v3.xml -t library_tag muscle-sn_S1_R2_001.fastq.gz muscle-sn_S1_R4_001.fastq.gz muscle-sn_S1_R1_001.fastq.gz muscle-sn_S1_R3_001.fastq.gz

Each time I use the commands, there is this answer : 

Total 5000000 read (0 parsed, 0 passed quality threshold)
Total 10000000 read (0 parsed, 0 passed quality threshold)
Total 15000000 read (0 parsed, 0 passed quality threshold)
Total 20000000 read (0 parsed, 0 passed quality threshold)
Total 25000000 read (0 parsed, 0 passed quality threshold)
Total 30000000 read (0 parsed, 0 passed quality threshold)
Total 35000000 read (0 parsed, 0 passed quality threshold)
Total 40000000 read (0 parsed, 0 passed quality threshold)
Total 45000000 read (0 parsed, 0 passed quality threshold)
Total 50000000 read (0 parsed, 0 passed quality threshold)
Total 55000000 read (0 parsed, 0 passed quality threshold)
Total 60000000 read (0 parsed, 0 passed quality threshold)
Total 65000000 read (0 parsed, 0 passed quality threshold)
Total 70000000 read (0 parsed, 0 passed quality threshold)
Total 75000000 read (0 parsed, 0 passed quality threshold)
Total 80000000 read (0 parsed, 0 passed quality threshold)
Total 85000000 read (0 parsed, 0 passed quality threshold)
Total 90000000 read (0 parsed, 0 passed quality threshold)
Total 95000000 read (0 parsed, 0 passed quality threshold)
Total 100000000 read (0 parsed, 0 passed quality threshold)
Total 105000000 read (0 parsed, 0 passed quality threshold)
Total 110000000 read (0 parsed, 0 passed quality threshold)
Total 115000000 read (0 parsed, 0 passed quality threshold)
Total 120000000 read (0 parsed, 0 passed quality threshold)
Total 125000000 read (0 parsed, 0 passed quality threshold)
Total 130000000 read (0 parsed, 0 passed quality threshold)
Total 135000000 read (0 parsed, 0 passed quality threshold)
Total 140000000 read (0 parsed, 0 passed quality threshold)
Total 145000000 read (0 parsed, 0 passed quality threshold)
Total 150000000 read (0 parsed, 0 passed quality threshold)
Total 155000000 read (0 parsed, 0 passed quality threshold)
Total 160000000 read (0 parsed, 0 passed quality threshold)
Total 165000000 read (0 parsed, 0 passed quality threshold)
Total 170000000 read (0 parsed, 0 passed quality threshold)
Total 175000000 read (0 parsed, 0 passed quality threshold)
Total 180000000 read (0 parsed, 0 passed quality threshold)
Total 185000000 read (0 parsed, 0 passed quality threshold)
Total 190000000 read (0 parsed, 0 passed quality threshold)
 (192478989 reads)
Outcomes:
[ (OK)  (Short read 1)  (Short read 2) ]
[0 0 0 ]
[0 0 0 ] %

	Trim stat:
[ (no trim)  (RC)  (PolyA)  (-A) ]
[0 0 0 0 ]
[-nan -nan -nan -nan ] %

Reading completed: 12:45:31.
Writing the rest lines
All done: 12:45:31.

Is there something wrong with my commands ?

Thank you very much by advance

**Comment by chlee-tabin** [comment]
I guess something like

```
droptag -p 8 -c /home/he/dropEst/configs/indrop_v3.xml -t library_tag["primary_d20_1"] muscle-sn_S1_R2_001.fastq.gz muscle-sn_S1_R4_001.fastq.gz muscle-sn_S1_R1_001.fastq.gz muscle-sn_S1_R3_001.fastq.gz
```

for each tags should be run.

**Comment by VPetukhov** [comment]
Thanks, @chlee-tabin!
Just need to add some parentheses:
```bash
droptag -p 8 -c /home/he/dropEst/configs/indrop_v3.xml -t ${library_tag["primary_d20_1"]} muscle-sn_S1_R2_001.fastq.gz muscle-sn_S1_R4_001.fastq.gz muscle-sn_S1_R1_001.fastq.gz muscle-sn_S1_R3_001.fastq.gz
```
