### ISSUE TITLE
DropEst for 10x 5'vdj data 

### ISSUE THREAD

**Issue by Zifeng1995** [hms-dbmi/dropEst#108]
HI,here
Is there any config.xml can be used for 10x 5' vdj BAM file? It seems that the 10x.xml can not be used in this data, because of the 5' data does not contain ploy A tails.

**Comment by VPetukhov** [comment]
Hi,
Poly-A tails matters only on the droptag phase, so it should play any role here. The only thing you really need to specify are the BAM tags for the cell barcode and UMI, which are `<cb>` and `<umi>` parts of [the config](https://github.com/hms-dbmi/dropEst/blob/master/configs/config_desc.xml#L68). And for using velocity (don't know if it's relevant for vdj) you also need the `<Type>` tag.

**Comment by Zifeng1995** [comment]
thanks，I solved it.

**Comment by msalaciak** [comment]
@Zifeng1995 

Hi! I'm trying to figure out the config.xml for 10x5' VDJ bam file as well...any chance you can share how you solved it?

thanks

**Comment by Zifeng-L** [comment]
> @Zifeng1995
> 
> Hi! I'm trying to figure out the config.xml for 10x5' VDJ bam file as well...any chance you can share how you solved it?
> 
> thanks

You can download the DropEst package and get the 10x_vdj.xml in configs. 
My codes as follows,
`dropest -V -f -g ./cellranger/refdata-cellranger-GRCh38-3.0.0/genes/genes.gtf -c ./dropEst-master/configs/10x_vdj.xml ./outs/possorted_genome_bam.bam`
