### ISSUE TITLE
bzip2 build and install

### ISSUE THREAD

**Issue by haircell** [hms-dbmi/dropEst#117]
Hi, 

I'm looking to install bzip2 with the following

```
wget http://www.bzip.org/1.0.6/bzip2-1.0.6.tar.gz # actually, I used link in closed issue #40 
tar xvf bzip2-1.0.6.tar.gz
cd bzip2-1.0.6
```
When I then run `make -f Makefile-libbz2_so`, I get the following error:
```
user/bzip2-1.0.6 % make -f Makefile-libbz2_so
gcc -fpic -fPIC -Wall -Winline -O2 -g -D_FILE_OFFSET_BITS=64 -c blocksort.c
gcc -fpic -fPIC -Wall -Winline -O2 -g -D_FILE_OFFSET_BITS=64 -c huffman.c
gcc -fpic -fPIC -Wall -Winline -O2 -g -D_FILE_OFFSET_BITS=64 -c crctable.c
gcc -fpic -fPIC -Wall -Winline -O2 -g -D_FILE_OFFSET_BITS=64 -c randtable.c
gcc -fpic -fPIC -Wall -Winline -O2 -g -D_FILE_OFFSET_BITS=64 -c compress.c
gcc -fpic -fPIC -Wall -Winline -O2 -g -D_FILE_OFFSET_BITS=64 -c decompress.c
gcc -fpic -fPIC -Wall -Winline -O2 -g -D_FILE_OFFSET_BITS=64 -c bzlib.c
gcc -shared -Wl,-soname -Wl,libbz2.so.1.0 -o libbz2.so.1.0.6 blocksort.o huffman.o crctable.o randtable.o compress.o decompress.o bzlib.o
ld: unknown option: -soname
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [all] Error 1
```

Any thoughts on how to get around this please? 

Thanks!

**Comment by evanbiederstedt** [comment]
If you're on your Mac (which I think is the case given the `-soname` error), you should probably explore installing this using more Mac-friendly ways, e.g. https://formulae.brew.sh/formula/bzip2

I'll try to remember to update the documentation about this. 

As to the error, it's something related to this I would guess: https://stackoverflow.com/questions/4580789/ld-unknown-option-soname-on-os-x

**Comment by haircell** [comment]
Thanks @evanbiederstedt. 
home brew went through ok.
