### ISSUE TITLE
question about config

### ISSUE THREAD

**Issue by kkamiii** [hms-dbmi/dropEst#118]
Hi,
I'm a student studying bioinformatics, and I'm trying to analysing public single cell data (indrop platform) with your great tool.

But, I don't understand some parameters parameters in config (.xml) file.

what is ..
max_spacer_edit_distance
spacer_search_length
r1_rc_length
min_align_length
poly_a_tail
min_merge_fraction
max_cb_merge_edit_distance
max_umi_merge_edit_distance 
..?

I'm so sad that I don't understand so many things..
Could you help me??

thank you!

**Comment by evanbiederstedt** [comment]
Hi there

There is a description file here: https://github.com/hms-dbmi/dropEst/blob/master/configs/config_desc.xml

Thanks, Evan
