### ISSUE TITLE
Can dropEst run nadia platform? (12 bp cellbarcode + 8 bp UMI)

### ISSUE THREAD

**Issue by amufaamo** [hms-dbmi/dropEst#129]
Hi, I am trying to use dropEst in nadia platform library.

The structure is 
R1: 12 bp cellbarcode + 8 bp UMI
R2: transcriptome

Can dropEst run with nadia platform?

**Comment by VPetukhov** [comment]
Hi, I didn't work with nadia, but the description looks exactly like DropSeq. Please try to take [their config](https://github.com/kharchenkolab/dropEst/blob/master/configs/drop_seq.xml) (see `MultipleBarcodeSearch` for the barcoding description). You may only need to update `BamTags` section depending on your alignment parameters.

**Comment by amufaamo** [comment]
OK, thank you. I will try it.
