### ISSUE TITLE
Cannot link to 

### ISSUE THREAD

**Issue by abhaduri** [hms-dbmi/dropEst#13]
When I try to install, I get the following errors that prevent installation in following steps. I want to know which libraries these packages are trying to link to so that I might specify the paths, but can't seem to figure out what the targets need. Any help would be appreciated. 

WARNING: Target "DropTools" requests linking to directory "/home/abhaduri/packages/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "Estimation" requests linking to directory "/home/abhaduri/packages/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "TestEstimation" requests linking to directory "/home/abhaduri/packages/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "TestEstimationMergeProbs" requests linking to directory "/home/abhaduri/packages/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "TestTagsSearch" requests linking to directory "/home/abhaduri/packages/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "TestTools" requests linking to directory "/home/abhaduri/packages/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "dropest" requests linking to directory "/home/abhaduri/packages/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "droptag" requests linking to directory "/home/abhaduri/packages/lib".  Targets may link only to libraries.  CMake is dropping the item.

**Comment by VPetukhov** [comment]
Did you use any specific make/cmake options? Can you also please specify your OS, cmake and compiler versions?

**Comment by VPetukhov** [comment]
Did you use any specific make/cmake options? Can you also please specify your OS, cmake and compiler versions?

**Comment by VPetukhov** [comment]
Did you use any specific make/cmake options? Can you also please specify your compiler version and to attach compilation logs?

**Comment by abhaduri** [comment]
I am working on a server with older installations of things so specified a number of options. I am using cmake version 2.8.12.2, compiler is version 6.1.1, and this is a 6.6 (Red Hat Enterprise Linux 6.6). 

Here is my command line: 

cmake -DCMAKE_INSTALL_PREFIX=/home/abhaduri/dropEst/ -DBoost_NO_BOOST_CMAKE=TRUE -DBoost_NO_SYSTEM_PATHS=TRUE -DBOOST_ROOT=/home/abhaduri/boost_1_61_0 -DR_LIBRARIES=/home/abhaduri/packages/lib/ -DR_ROOT=/home/abhaduri/R-3.4.1/

**Comment by abhaduri** [comment]
And here is the output of cmake: 

cmake -DCMAKE_INSTALL_PREFIX=/home/abhaduri/dropEst/ -DBoost_NO_BOOST_CMAKE=TRUE -DBoost_NO_SYSTEM_PATHS=TRUE -DBOOST_ROOT=/home/abhaduri/boost_1_61_0 -DR_LIBRARIES=/home/abhaduri/packages/lib/ -DR_ROOT=/home/abhaduri/R-3.4.1/
-- Boost version: 1.61.0
-- Found the following Boost libraries:
--   filesystem
--   iostreams
--   log
--   system
--   thread
--   unit_test_framework
-- ** Boost Include: /home/abhaduri/boost_1_61_0
-- ** Boost Libraries: /home/abhaduri/boost_1_61_0/stage/lib
-- ** Boost Link-Libs: /home/abhaduri/boost_1_61_0/stage/lib/libboost_filesystem.so;/home/abhaduri/boost_1_61_0/stage/lib/libboost_iostreams.so;/home/abhaduri/boost_1_61_0/stage/lib/libboost_log.so;/home/abhaduri/boost_1_61_0/stage/lib/libboost_system.so;/home/abhaduri/boost_1_61_0/stage/lib/libboost_thread.so;/home/abhaduri/boost_1_61_0/stage/lib/libboost_unit_test_framework.so
-- Could not find libR shared library.
-- Found R: /home/abhaduri/R-3.4.1/
-- Configuring done
WARNING: Target "DropTools" requests linking to directory "/home/abhaduri/packages/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "Estimation" requests linking to directory "/home/abhaduri/packages/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "TestEstimation" requests linking to directory "/home/abhaduri/packages/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "TestEstimationMergeProbs" requests linking to directory "/home/abhaduri/packages/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "TestTagsSearch" requests linking to directory "/home/abhaduri/packages/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "TestTools" requests linking to directory "/home/abhaduri/packages/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "dropest" requests linking to directory "/home/abhaduri/packages/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "droptag" requests linking to directory "/home/abhaduri/packages/lib".  Targets may link only to libraries.  CMake is dropping the item.
-- Generating done
-- Build files have been written to: /home/abhaduri/dropEst

**Comment by VPetukhov** [comment]
When you set "-DR_LIBRARIES" you need to specify path to library files, not just a directory. Currently, the pipeline uses *libR.so* and *libRInside.so*. But normally you shouldn't set this path by yourself. If you have packages in a separate folder, please, try to set "R_PACKAGES_DIRS" (see *dropEst/CMake/FindR.cmake*). But it shouldn't be the case if your R installation is in the $PATH. Did you try to simply remove "-DR_LIBRARIES" option?

**Comment by abhaduri** [comment]
Yeah, my R installation is not in the $PATH but I get the same error when removing -DR_LIBRARIES as well as when using R_PACKAGES_DIRS. I think I might need to reconfigure my R installation as I cannot find libR.so and libRInside.so - thank you so much!

**Comment by VPetukhov** [comment]
You're welcome!
Did you remove the files from your previous cmake prior to run it with new options? It normally caches the result and ignores all changes. If your R executable is located at "*/home/abhaduri/R-3.4.1/bin/R*" it should be enough to set R_ROOT as you do it now (-DR_ROOT=/home/abhaduri/R-3.4.1/).

**Comment by abhaduri** [comment]
Yes, I did all of the above, but now have the issue where it cannot find the libR shared library. It seems this may be an issue with how I installed my R so may need to reinstall it.

**Comment by abhaduri** [comment]
Thanks so much- I had to reinstall R with --enable-R-sh and it worked!
