### ISSUE TITLE
build fails at 36% (boost)

### ISSUE THREAD

**Issue by nachocab** [hms-dbmi/dropEst#14]
Hi,

I've been trying to build dropEst, but I keep running against these errors:

    Scanning dependencies of target droptag
    [ 34%] Building CXX object CMakeFiles/droptag.dir/droptag.cpp.o
    [ 36%] Linking CXX executable droptag
    libDropTools.a(Logs.cpp.o): In function `boost::log::v2_mt_posix::sinks::synchronous_sink<boost::log::v2_mt_posix::sinks::text_file_backend>::consume(boost::log::v2_mt_posix::record_view const&)':
    Logs.cpp:(.text._ZN5boost3log11v2_mt_posix5sinks16synchronous_sinkINS2_17text_file_backendEE7consumeERKNS1_11record_viewE[_ZN5boost3log11v2_mt_posix5sinks16synchronous_sinkINS2_17text_file_backendEE7consumeERKNS1_11record_viewE]+0x2ba): undefined reference to `boost::log::v2_mt_posix::sinks::text_file_backend::consume(boost::log::v2_mt_posix::record_view const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
    libDropTools.a(Logs.cpp.o): In function `boost::log::v2_mt_posix::sinks::synchronous_sink<boost::log::v2_mt_posix::sinks::basic_text_ostream_backend<char> >::consume(boost::log::v2_mt_posix::record_view const&)':
    Logs.cpp:(.text._ZN5boost3log11v2_mt_posix5sinks16synchronous_sinkINS2_26basic_text_ostream_backendIcEEE7consumeERKNS1_11record_viewE[_ZN5boost3log11v2_mt_posix5sinks16synchronous_sinkINS2_26basic_text_ostream_backendIcEEE7consumeERKNS1_11record_viewE]+0x2ba): undefined reference to `boost::log::v2_mt_posix::sinks::basic_text_ostream_backend<char>::consume(boost::log::v2_mt_posix::record_view const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
    libDropTools.a(Logs.cpp.o): In function `void boost::log::v2_mt_posix::basic_formatting_ostream<char, std::char_traits<char>, std::allocator<char> >::aligned_write<wchar_t>(wchar_t const*, long)':
    Logs.cpp:(.text._ZN5boost3log11v2_mt_posix24basic_formatting_ostreamIcSt11char_traitsIcESaIcEE13aligned_writeIwEEvPKT_l[_ZN5boost3log11v2_mt_posix24basic_formatting_ostreamIcSt11char_traitsIcESaIcEE13aligned_writeIwEEvPKT_l]+0x77): undefined reference to `boost::log::v2_mt_posix::aux::code_convert(wchar_t const*, unsigned long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::locale const&)'
    Logs.cpp:(.text._ZN5boost3log11v2_mt_posix24basic_formatting_ostreamIcSt11char_traitsIcESaIcEE13aligned_writeIwEEvPKT_l[_ZN5boost3log11v2_mt_posix24basic_formatting_ostreamIcSt11char_traitsIcESaIcEE13aligned_writeIwEEvPKT_l]+0xf1): undefined reference to `boost::log::v2_mt_posix::aux::code_convert(wchar_t const*, unsigned long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::locale const&)'
    libDropTools.a(Logs.cpp.o): In function `void boost::log::v2_mt_posix::type_dispatcher::callback_base::trampoline<boost::log::v2_mt_posix::binder1st<boost::log::v2_mt_posix::output_fun, boost::log::v2_mt_posix::expressions::aux::stream_ref<boost::log::v2_mt_posix::basic_formatting_ostream<char, std::char_traits<char>, std::allocator<char> > >&>, std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > >(void*, std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > const&)':
    Logs.cpp:(.text._ZN5boost3log11v2_mt_posix15type_dispatcher13callback_base10trampolineINS1_9binder1stINS1_10output_funERNS1_11expressions3aux10stream_refINS1_24basic_formatting_ostreamIcSt11char_traitsIcESaIcEEEEEEENSt7__cxx1112basic_stringIwSB_IwESaIwEEEEEvPvRKT0_[_ZN5boost3log11v2_mt_posix15type_dispatcher13callback_base10trampolineINS1_9binder1stINS1_10output_funERNS1_11expressions3aux10stream_refINS1_24basic_formatting_ostreamIcSt11char_traitsIcESaIcEEEEEEENSt7__cxx1112basic_stringIwSB_IwESaIwEEEEEvPvRKT0_]+0x5e): undefined reference to `boost::log::v2_mt_posix::aux::code_convert(wchar_t const*, unsigned long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::locale const&)'
    libDropTools.a(Logs.cpp.o): In function `boost::log::v2_mt_posix::sinks::synchronous_sink<boost::log::v2_mt_posix::sinks::text_file_backend>::try_consume(boost::log::v2_mt_posix::record_view const&)':
    Logs.cpp:(.text._ZN5boost3log11v2_mt_posix5sinks16synchronous_sinkINS2_17text_file_backendEE11try_consumeERKNS1_11record_viewE[_ZN5boost3log11v2_mt_posix5sinks16synchronous_sinkINS2_17text_file_backendEE11try_consumeERKNS1_11record_viewE]+0x2d8): undefined reference to `boost::log::v2_mt_posix::sinks::text_file_backend::consume(boost::log::v2_mt_posix::record_view const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
    libDropTools.a(Logs.cpp.o): In function `boost::log::v2_mt_posix::sinks::synchronous_sink<boost::log::v2_mt_posix::sinks::basic_text_ostream_backend<char> >::try_consume(boost::log::v2_mt_posix::record_view const&)':
    Logs.cpp:(.text._ZN5boost3log11v2_mt_posix5sinks16synchronous_sinkINS2_26basic_text_ostream_backendIcEEE11try_consumeERKNS1_11record_viewE[_ZN5boost3log11v2_mt_posix5sinks16synchronous_sinkINS2_26basic_text_ostream_backendIcEEE11try_consumeERKNS1_11record_viewE]+0x2d8): undefined reference to `boost::log::v2_mt_posix::sinks::basic_text_ostream_backend<char>::consume(boost::log::v2_mt_posix::record_view const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
    collect2: error: ld returned 1 exit status
    make[2]: *** [droptag] Error 1
    make[1]: *** [CMakeFiles/droptag.dir/all] Error 2
    make: *** [all] Error 2

This was my configuration output:

    /share/pkg/cmake/3.10.0/install/bin/cmake \
    >  -DCMAKE_C_COMPILER=/share/pkg/gcc/7.2.0/install/bin/gcc \
    >  -DCMAKE_CXX_COMPILER=/share/pkg/gcc/7.2.0/install/bin/g++ \
    >  -D R_ROOT="/share/pkg/r/3.4.2/install/lib64/R" \
    >  -D BOOST_ROOT="/share/pkg/boost/1.57.0/install" \
    >  .
    -- The C compiler identification is GNU 7.2.0
    -- The CXX compiler identification is GNU 7.2.0
    -- Check for working C compiler: /share/pkg/gcc/7.2.0/install/bin/gcc
    -- Check for working C compiler: /share/pkg/gcc/7.2.0/install/bin/gcc -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Check for working CXX compiler: /share/pkg/gcc/7.2.0/install/bin/g++
    -- Check for working CXX compiler: /share/pkg/gcc/7.2.0/install/bin/g++ -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- Looking for pthread.h
    -- Looking for pthread.h - found
    -- Looking for pthread_create
    -- Looking for pthread_create - not found
    -- Looking for pthread_create in pthreads
    -- Looking for pthread_create in pthreads - not found
    -- Looking for pthread_create in pthread
    -- Looking for pthread_create in pthread - found
    -- Found Threads: TRUE
    -- Boost version: 1.57.0
    -- Found the following Boost libraries:
    --   filesystem
    --   iostreams
    --   log
    --   system
    --   thread
    --   unit_test_framework
    --   regex
    --   log_setup
    --   date_time
    --   chrono
    --   atomic
    -- ** Boost Include: /share/pkg/boost/1.57.0/install/include
    -- ** Boost Libraries: /share/pkg/boost/1.57.0/install/lib
    -- ** Boost Link-Libs: /share/pkg/boost/1.57.0/install/lib/libboost_filesystem.so;/share/pkg/boost/1.57.0/install/lib/libboost_iostreams.so;/share/pkg/boost/1.57.0/install/lib/libboost_log.so;/share/pkg/boost/1.57.0/install/lib/libboost_system.so;/share/pkg/boost/1.57.0/install/lib/libboost_thread.so;/share/pkg/boost/1.57.0/install/lib/libboost_unit_test_framework.so;/share/pkg/boost/1.57.0/install/lib/libboost_regex.so;/share/pkg/boost/1.57.0/install/lib/libboost_log_setup.so;/share/pkg/boost/1.57.0/install/lib/libboost_date_time.so;/share/pkg/boost/1.57.0/install/lib/libboost_chrono.so;/share/pkg/boost/1.57.0/install/lib/libboost_atomic.so
    -- Found ZLIB: /usr/lib64/libz.so (found version "1.2.3")
    -- Found BAMTOOLS: /share/pkg/bamtools/2.4.0/install/bin/../lib/libbamtools.so
    -- Found R: /share/pkg/r/3.4.2/install/lib64/R/lib/libR.so
    -- Found R: /share/pkg/r/3.4.2/install/lib64/R
    -- Configuring done
    -- Generating done
    -- Build files have been written to: /my/path/dropEst/dropEst

Any advice?

**Comment by VPetukhov** [comment]
Did you try to set LD_LIBRARY_PATH variable to the boost `lib` directory prior to building?
```bash
export LD_LIBRARY_PATH="/share/pkg/boost/1.57.0/install/lib/:$LD_LIBRARY_PATH"
make ./
```

**Comment by nachocab** [comment]
@VPetukhov I did. No difference

**Comment by VPetukhov** [comment]
@nachocab 
Can you please paste the output of `ls /share/pkg/boost/1.57.0/install/lib/`?

**Comment by nachocab** [comment]
Here you go

    ls /share/pkg/boost/1.57.0/install/lib/
    libboost_atomic.a             libboost_filesystem.a          libboost_math_c99f.a          libboost_prg_exec_monitor.so.1.57.0  libboost_system.a
    libboost_atomic.so            libboost_filesystem.so         libboost_math_c99f.so         libboost_program_options.a           libboost_system.so
    libboost_atomic.so.1.57.0     libboost_filesystem.so.1.57.0  libboost_math_c99f.so.1.57.0  libboost_program_options.so          libboost_system.so.1.57.0
    libboost_chrono.a             libboost_graph.a               libboost_math_c99l.a          libboost_program_options.so.1.57.0   libboost_test_exec_monitor.a
    libboost_chrono.so            libboost_graph.so              libboost_math_c99l.so         libboost_python.a                    libboost_thread.a
    libboost_chrono.so.1.57.0     libboost_graph.so.1.57.0       libboost_math_c99l.so.1.57.0  libboost_python.so                   libboost_thread.so
    libboost_container.a          libboost_iostreams.a           libboost_math_c99.so          libboost_python.so.1.57.0            libboost_thread.so.1.57.0
    libboost_container.so         libboost_iostreams.so          libboost_math_c99.so.1.57.0   libboost_random.a                    libboost_timer.a
    libboost_container.so.1.57.0  libboost_iostreams.so.1.57.0   libboost_math_tr1.a           libboost_random.so                   libboost_timer.so
    libboost_context.a            libboost_locale.a              libboost_math_tr1f.a          libboost_random.so.1.57.0            libboost_timer.so.1.57.0
    libboost_context.so           libboost_locale.so             libboost_math_tr1f.so         libboost_regex.a                     libboost_unit_test_framework.a
    libboost_context.so.1.57.0    libboost_locale.so.1.57.0      libboost_math_tr1f.so.1.57.0  libboost_regex.so                    libboost_unit_test_framework.so
    libboost_coroutine.a          libboost_log.a                 libboost_math_tr1l.a          libboost_regex.so.1.57.0             libboost_unit_test_framework.so.1.57.0
    libboost_coroutine.so         libboost_log_setup.a           libboost_math_tr1l.so         libboost_serialization.a             libboost_wave.a
    libboost_coroutine.so.1.57.0  libboost_log_setup.so          libboost_math_tr1l.so.1.57.0  libboost_serialization.so            libboost_wave.so
    libboost_date_time.a          libboost_log_setup.so.1.57.0   libboost_math_tr1.so          libboost_serialization.so.1.57.0     libboost_wave.so.1.57.0
    libboost_date_time.so         libboost_log.so                libboost_math_tr1.so.1.57.0   libboost_signals.a                   libboost_wserialization.a
    libboost_date_time.so.1.57.0  libboost_log.so.1.57.0         libboost_prg_exec_monitor.a   libboost_signals.so                  libboost_wserialization.so
    libboost_exception.a          libboost_math_c99.a            libboost_prg_exec_monitor.so  libboost_signals.so.1.57.0           libboost_wserialization.so.1.57.0

And the second one:

    ls -la /share/pkg/boost/1.57.0/install/lib/libboost_log.so

    lrwxrwxrwx 1 yannpaul scv 22 Mar 25  2015 /share/pkg/boost/1.57.0/install/lib/libboost_log.so -> libboost_log.so.1.57.0

**Comment by nachocab** [comment]
My sysadmin was able to fix this. It turns out that our version of R was compiled using gcc 5.3.0 and boost was compiled with g++ 4.4.7. He recompiled boost with 5.3.0 and the error went away.
