### ISSUE TITLE
When to use dropEst multiple bam input

### ISSUE THREAD

**Issue by ahy1221** [hms-dbmi/dropEst#15]
I am  confused about the usage of dropEst about how merging data from different samples when I found that  it accepts multiple bams as input.
Assume I generated two 10X libraries from two samples , I ran the cellranger then I got two bams.
The question is that should I input these two bams for dropEst if I want to analysis them as one matrix ?
Or I should merge these two matrices after dropEst and dropEstR filtered ?

**Comment by VPetukhov** [comment]
If your bams were generated from different samples you need to merge matrices after dropEst. Otherwise, cells from different libraries with the same barcodes will be considered as the same cells.
