### ISSUE TITLE
Problems with Debyan docker image 

### ISSUE THREAD

**Issue by lucacozzuto** [hms-dbmi/dropEst#19]
Hi,
after built the docker image I was not able to run it since I got following error:

docker run -ti  --name dropest dropest /bin/bash

/bin/bash: /bin/bash: cannot execute binary file

I fix it by commenting this part in the Docker file:

#ENTRYPOINT ["/bin/bash"]

Best,
Luca

**Comment by VPetukhov** [comment]
Hi Luca,

Did you try to run `docker run -ti --name dropest dropest`? It works fine for me.

**Comment by lucacozzuto** [comment]
Many thanks! I was not aware of this use of ENTRYPOINT.
