### ISSUE TITLE
Error with dropReport.Rsc

### ISSUE THREAD

**Issue by lucacozzuto** [hms-dbmi/dropEst#20]
Dear developers,
I got this error at the end of the procedure and I don't know how to solve it:

./dropReport.Rsc SRR1784313.est.rds -o $HOME/report.html 

processing file: report.Rmd
  |..                                                               |   3%
   inline R code fragments

  |....                                                             |   6%
label: unnamed-chunk-1 (with options) 
List of 1
 $ include: logi FALSE

Error in file(file, ifelse(append, "a", "w")) : 
  cannot open the connection
Calls: <Anonymous> ... withCallingHandlers -> withVisible -> eval -> eval -> library
In addition: Warning message:
In file(file, ifelse(append, "a", "w")) :
  cannot open file 'report.knit.md': Permission denied

Execution halted

PS: I am using the docker image for debyan. 

Can you help me, please?

**Comment by VPetukhov** [comment]
Dear Luca,
Sorry for the delay. You're right, dockers have problems with dropReport. I fixed debian docker and hope fix the others soon.

**Comment by lucacozzuto** [comment]
Thanks a lot for this! However I have more questions about this nice tool. Do you have a gitter chat, or a google group for answering? Or should I make the question here? (It is mainly about the R package you made it).

**Comment by VPetukhov** [comment]
No, we don't have a chat. Please, open an issue with some general title. Indeed, it's really an issue because we still need to write dropestr section in the README. Perhaps, I will move some of answers to your questions there.

**Comment by lucacozzuto** [comment]
Wonderful! Thanks!

**Comment by VPetukhov** [comment]
Finally fixed all dockers in da974df.
