### ISSUE TITLE
problem with dropReport.Rsc

### ISSUE THREAD

**Issue by lucacozzuto** [hms-dbmi/dropEst#22]
Dear developers,
once installed dropReport.Rsc I manged to have the report in html but I cannot when I use -t option and providing the tagged rds file.
I got the following error:
label: unnamed-chunk-9 (with options) 
List of 2
 $ fig.width : num 5
 $ fig.height: num 3

  |...................................                              |  54%
  ordinary text without R code

  |.....................................                            |  57%
label: unnamed-chunk-10
Quitting from lines 95-97 (report.Rmd) 
Error in total.reads.per.cell[merge.targets] : 
  invalid subscript type 'list'
Calls: <Anonymous> ... eval -> ScorePipelineCells -> PrepareLqCellsDataPipeline
In addition: Warning messages:
1: In bind_rows_(x, .id) : Unequal factor levels: coercing to character
2: In bind_rows_(x, .id) :
  binding character and factor vector, coercing into character vector
3: In bind_rows_(x, .id) :
  binding character and factor vector, coercing into character vector
4: In bind_rows_(x, .id) : Unequal factor levels: coercing to character
5: In bind_rows_(x, .id) :
  binding character and factor vector, coercing into character vector
6: In bind_rows_(x, .id) :
  binding character and factor vector, coercing into character vector
7: In bind_rows_(x, .id) :
  binding character and factor vector, coercing into character vector
8: In bind_rows_(x, .id) :
  binding character and factor vector, coercing into character vector
9: Removed 1 rows containing missing values (geom_bar). 

Execution halted

**Comment by VPetukhov** [comment]
Please, check the updated version (commit eaf04118e66c14324c196eb01991c5cd7d3160dd).
