### ISSUE TITLE
Extract High Quality Cells

### ISSUE THREAD

**Issue by dylanmr** [hms-dbmi/dropEst#23]
Hi,

I have run the pipeline and have gotten great data. However, I am a little but stuck trying to extract high quality cells from the filtered count matrix in R. I can see the cells qualified as high quality in dropreport, but cant seem to find cell rank in any of the rds files. Any advice on how to better extract high quality cells? 

Best, 
Dylan

**Comment by dylanmr** [comment]
I actually found this vignette which was very helpful!

https://vpetukhov.github.io/dropEstAnalysis/annotation__annotation_bmmc1.html

**Comment by VPetukhov** [comment]
`dropEstAnalysis` repo is under development, so I didn't link it here. Vignette on low-quality cells in `dropestr` package (https://github.com/hms-dbmi/dropEst/blob/master/dropestr/vignettes/low-quality-cells.Rmd) was assumed to explain how to score cells.

**Comment by zh542370159** [comment]
I am using the following codes to extract the cells that have high quality and a score>0.9 :
```
dropest <- readRDS("cell.counts.rds")
cell_num <- EstimateCellsNumber(dropest$aligned_umis_per_cell)
lq_cells_df <- PrepareLqCellsDataPipeline(data = dropest,mit.chromosome.name = "chrM")
scores <- ScoreQualityData(umi.counts = dropest$aligned_umis_per_cell, 
                           scoring.data = lq_cells_df, cell.number = cell_num)
qualified <- intersect(
  x = names(sort(dropest$aligned_umis_per_cell, decreasing = TRUE)[1:cell_num$min]),
  y = names(scores[scores > 0.9])
)
```
