### ISSUE TITLE
Statistics about mapping

### ISSUE THREAD

**Issue by elimereu** [hms-dbmi/dropEst#3]
Hi,
In my lab, we sequenced for the first time some libraries by using the SeqWell protocol. 
Then I ran the Dropseq pipeline to get my count matrix. But, I would like to have some statistics about the mapping, for example number of exonic, intronic and intergenic reads. 
After the alignment step I got a unique bam file for all barcodes. Is there a way to run dropEst with this bam file to get these statistics per CB? 

Thank you, 

Elisabetta

**Comment by VPetukhov** [comment]
Dear Elisabetta,

Thank you for your interest to the pipeline.  
Yes, you can use Drop-seq .bam file as intput to dropEst (see [Usage of tagged bam files (e.g. 10x, Drop-seq) as input](https://github.com/hms-dbmi/dropEst#usage-of-tagged-bam-files-eg-10x-drop-seq-as-input)). Afterward, you'll get .rds file with different statistics. Particularly, number of exonic/intronic reads per cell is stored in **reads_per_chr_per_cell** field (see [Output](https://github.com/hms-dbmi/dropEst#output)). Though, the information there is grouped by chromosomes, so you need to use code like this: 
```r
rds <- readRDS('cell.counts.rds')
reads_per_cell <- lapply(rds$reads_per_chr_per_cells, function(x) rowSums(x)[colnames(rds$cm)])
df <- data.frame(reads_per_cell)
df[is.na(df)] <- 0
```
If you need some additional stats, please either look at dropReport.Rsc or ask me. The pipeline is still under development and some rds fields can be changed, so they are not well-documented now.  
P.S. Please, ensure that you are using the latest version of the pipeline, i.e. 0.6.8.

Kind regards,  
Viktor Petukhov

**Comment by zhuo91** [comment]
Dear Viktor Petukhov,
I am also using the dropEst to process my dropseq aligned bam files, however the Exon matrix looks a bit weird. From the example file in the tutorial, I noticed that the Exon matrix is 6x6000. However, my Exon matrix in rds$reads_per_chr_per_cells looks like this:

> dim(rds$reads_per_chr_per_cells$Exon)
[1] 20777    22

> head(rds$reads_per_chr_per_cells$Exon)
              Y   X   MT   9   8   7   6   5   4   3   2   1  13  12  11  10
GAATGAAAGTAT  0 296 1847 404 150 492 287 310 333 527 318 251 187 207 656 373
CCCCCATCGCTC 13  24   61  52  17 102  23 655  39  30  36  42  20  11 143  36
CTAGCCATATAC  0  43  107  33  34  90  45  71  83  48  58  30  12  58 106  89
AACACCGCTGCT  0 374 5521 718 320 898 410 562 590 846 635 488 288 308 896 627
CCCTTGGTCTAA  0 218 1160 254 196 575 227 350 242 225 348 208  84 198 576 279
TAAGTGCGCACA  0   0    1   2   1   2   1   2   4   1   5   7   2   2   0  16
              14  15  16  17  18  19
GAATGAAAGTAT 227 210 145 318 152 181
CCCCCATCGCTC  17  71  22  25  10  30
CTAGCCATATAC  40  20  11  65  18  70
AACACCGCTGCT 308 404 198 711 219 303
CCCTTGGTCTAA 166 149 140 488  96 221
TAAGTGCGCACA   0   2   1  10   0   8

After running the following 3 lines:

reads_per_cell <- lapply(rds$reads_per_chr_per_cells, function(x) rowSums(x)[colnames(rds$cm)])

df <- data.frame(reads_per_cell)

df[is.na(df)] <- 0

I got 
> head(df)
             Exon Intron Intergenic
CCGTCAACTTGC  338     35        116
GGATGGAATTAG  212     36         47
ACCGCTCACACT  255     78         55
CCCCCACTGCCC  235    239        221
CGTATTACACAA  265    193         71
CCGCCCGCGTTC  269     71        193

Shall I use df$Exon for downstream analysis? It is numeric without information of individual genes, so I guess something is wrong. Your advice is highly appreciated! @VPetukhov 

Thanks!
Zhuo

**Comment by zhuo91** [comment]
Dear Elisabetta,

Have you got your your dropseq file work for dropEst? Did you use the STAR aligned, gene exon tagged bam file? I'd really appreciate it if you can share some experience in using dropEst on dropseq files. @elimereu 

Thanks a million,
Zhuo

**Comment by elimereu** [comment]
Hi Zhuo, 

to be honest it’s still something I have to try and I will do it soon. 
So, I cannot help you at the moment but whenever I have something I’ll tell you. 
I’m sorry about that. 

All the best, 

Elisabetta

--
Elisabetta Mereu, PhD
Genomic Data Scientist
Single Cell Genomics Group
Centro Nacional de Análisis Genómico
Centre de Regulació Genomica (CNAG-CRG)
web: http://www.cnag.cat <http://www.cnag.cat/>

**Comment by VPetukhov** [comment]
Dear Zhuo,
Field `reads_per_chr_per_cells` means "reads per chromosome per cell", so it's alright that you have matrix with data by chromosome. It was created to use it in `PlotIntergenicFractionByChromosomes` and to extract fraction of mitochondrial reads in low-quality cells classification. To get number of UMIs for each gene, please use `cm` field (which means "count matrix", perhaps I'll rename it in the future). There is also field `cm_raw`, which has the same data as `cm`, but without some filtration.

**Comment by zhuo91** [comment]
Dear Viktor Petukhov,
Thanks for the clarification. I think my main question is "where to find exon and intron matrices in my processed dropseq data, since there are no field called 'exon' nor 'intron'"? Can you provide some instructions? Thanks a lot! -Zhuo

**Comment by zhuo91** [comment]
@VPetukhov The following are the fields in my rds file:

> names(rds)
 [1] "cm"                      "cm_raw"                 
 [3] "reads_per_chr_per_cells" "reads_per_umi_per_cell" 
 [5] "mean_reads_per_umi"      "saturation_info"        
 [7] "merge_targets"           "aligned_reads_per_cell" 
 [9] "aligned_umis_per_cell"   "requested_umis_per_cb"  
[11] "requested_reads_per_cb"

**Comment by zhuo91** [comment]
Problem solved. It turns out I did not add the -V option when using dropEst, so only the "cell.counts.rds" was output. The correct data to use for velocyto is "cell.counts.matrices.rds", which only present if adding the -V option.
