### ISSUE TITLE
Splitting large bam file before processing - any associated issues?

### ISSUE THREAD

**Issue by nicolaromano** [hms-dbmi/dropEst#31]
I am processing a fairly large bam file for use in velocyto, using dropEst with the -V option. 

My issue is that the file is too big for my computer to process, so half the way through everything hangs and I cannot finish the processing (after a while the system hangs, then aborts the process before any output is written)...

I have tried subsampling the file using sambamba and I can run the whole thing with the smaller bam file, suggesting the issue is not in the file itself or in the way I use dropEst. My idea is therefore to split the bam file in smaller chunks, for example by splitting it by chromosome, then run dropEst on each of them then merge the output matrices in R. 

Could you advise on whether this is a sensible thing to do, or whether there could be issues in proceeding in this way?

**Comment by VPetukhov** [comment]
Hello,
You can have problems with CB/UMI correction, as it assumes that the pipeline has all data about each cell. Do you have list of real CBs? Or are you using bam file from CellRanger output? If it's the case, I'd suggest just to set all filtration thresholds in the config to a very small value (10 or even 0). As the result you'll get very large count matrices, so after merging them you need to filter them by hands. [Here](https://vpetukhov.github.io/dropEstAnalysis/low_quality_cells__validation_mouse_pc.html#pipeline_data) is demonstration on how I merged InDrop datasets, and [here](https://vpetukhov.github.io/dropEstAnalysis/low_quality_cells__validation_mouse_pc.html#number_of_cells) is an example of how you can determine number of cells.
Please, keep in mind that if you disable all filtration, by default pipeline saves **all** information about UMIs to the .rds file for subsequent error correction. It probably again will take all your memory. To prevent this behaviour use "-u" for using more simple and efficient UMI correction algorithm. With this option, UMIs are corrected during dropest phase, and correction information isn't saved to .rds.

**Comment by nicolaromano** [comment]
Hi, thank you for your prompt reply. I am using the bam output from CellRanger and, yes I have a list of real CBs. I realise I should have specified that in the config file, my bad for not reading instructions correctly!

Another question: I have already previously processed my data with Seurat so I also have a filtered list of CBs, would it be problematic to use that?
