### ISSUE TITLE
DropEst for 10x single cell sequence data for velocyto.R

### ISSUE THREAD

**Issue by ayumatsubo** [hms-dbmi/dropEst#32]
Hi,

I'm trying DropEst in the 10X scRNAseq data (https://support.10xgenomics.com/single-cell-gene-expression/datasets/2.1.0/neurons_900) for velocyto on Docker. But there is no result file after running.
My code is following:

`dropest -V -f -g refdata-cellranger-mm10-1.2.0/genes/genes.gtf -c config_desc.xml neurons_900_possorted_genome_bam.bam`

and standard output is following:
 Version: 0.8.3.
 Run: 07/13/2018 09:30:55.
 config_desc.xml(43): expected =

Could you help me?

**Comment by VPetukhov** [comment]
Hi,

Did you change the config file? Because normally for 10x you should use 10x.xml config.

**Comment by ayumatsubo** [comment]
Thank you for replying. I also used 10x.xml, but the result was same.

**Comment by VPetukhov** [comment]
Can't reproduce your problem. Can you please run the code on 10x.xml from the repo and attach your log and genes.gtf here? And can you please also send the link on the docker you use?

**Comment by ayumatsubo** [comment]
I'm sorry. It's a simple problem. 10x.xml file is not correct.
I solved it.
Thank you a lot!
