### ISSUE TITLE
dropest "wrong quality length"

### ISSUE THREAD

**Issue by darneson** [hms-dbmi/dropEst#35]
I am trying to run dropest on my .bam file generated from DropSeq and get the following error:
Start parsing of bams: 22:06:27.
Wrong quality length: 0, expected: 5

I am not sure what this is in reference to, is it something to do with my bam file? Any help would be much appreciated.

**Comment by VPetukhov** [comment]
One possible reason is wrong UMI quality tag in the config. Please double-check that the tag, specified in the config.xml (or default tag if nothing is specified) is the same as real quality tag in the bam (see _"configs/config_desc.xml"_).

**Comment by DRLaks** [comment]
I am having the same issue with Dropest version 0.8.3 . The config file has the correct bam tags: XC for cell barcode, XM for UMI, The gene should be GE not XG but either way it doesn't work and gives the same error: Wrong quality length: 0, expected: 5. Is this a problem with this version of Dropest or is there something I can remedy. Thank you for your attention to this matter. All the best, Dan

**Comment by darneson** [comment]
I was able to resolve the issue. If you start from .bam files generated by DropSeq Tools, you will get this issue because dropEST expects tags in your .bam file corresponding to your cell barcode and umi sequence qualities (DropSeq tools only generates a single integer describing the overall umi quality which is not compatible ). There are currently no functions in DropSeq tools to do this directly so you have to write your own script to add these tags to your bam file and then it works as expected.

**Comment by DRLaks** [comment]
Thanks darneson I will check that out.

**Comment by DRLaks** [comment]
It seems from here: http://mccarrolllab.com/wp-content/uploads/2015/05/DropSeqInformaticsCookbook_v1.0_May2015.pdf   the tag_name parameter provides the appropriate bam tags. I don't see the issue of no bam tags from the dropseq tools. Can anyone elaborate?

**Comment by darneson** [comment]
Hi Dan,

This is what a few lines from a .bam file using DropSeq Tools would look like:

YAP050_2_1104_1_001605021	16	10	3102131	1	2S24M	*	0	0	AAACTTATCCAGGAAAAGCACTGGGG	--<JJFFAAJAA77777<AAFFA<<<	XC:Z:GGCCGTTTCGCG	MD:Z:24	XF:Z:INTERGENIC	PG:Z:STAR	RG:Z:A	NH:i:4	NM:i:0	XM:Z:CTCCAGGC	ZP:i:27	UQ:i:0	AS:i:23
YAP050_2_2204_1_001398069	16	10	3102974	1	68S33M	*	0	0	ATTTTCCTCTTTGGAGCTGACTGGTGGTTATTAAGGGTGGAATGGTTATTTTCAGGAAAGTTATGGCTGTTGATAGTGGTGTCTTGGTTTCTGGAATAAGC	<A<JAF<F7-A)JJJF7<JF77-7<---A7-AAFJAAFAFFA<A7-<-7--<JJJJJFJA7<FF7A7-7--FA<FAFA7JJJFFFJF<AJJJJJFF-<<<A	XC:Z:AGTACCTCAGAC	MD:Z:33	XF:Z:INTERGENIC	PG:Z:STAR	RG:Z:A	NH:i:3	NM:i:0	XM:Z:TTCAACGG	UQ:i:0	AS:i:32
YAP050_2_1204_1_001062862	16	10	3103714	3	66S35M	*	0	0	GGATTAAAGGCGTGCACCACCACCACCTGGCCCATCAAACTTCTGAACGCAGTGAGAAAAAAACCACAGGCAATCAAAAGGAATGAACTGCAGAAGTTTAG	--A<7<7))-7-)7))))))7))-)7-)))7AFA-AF-F777-7-7))--A7-A-FFF<J<A7-7-<J7JAF7--FF-JJJJAA<JJ7--FFFJAFA-<<A	XC:Z:GAATAATCAGGC	MD:Z:23T11	XF:Z:INTERGENIC	PG:Z:STAR	RG:Z:A	NH:i:2	NM:i:1	XM:Z:GCTGGGGG	UQ:i:12	AS:i:32

We have our cell barcode as XC and our UMI as XM, however my understanding is that dropEST requires the quality scores of these two barcodes (these are not added as tags using the traditional DropSeq tools workflow)

I got some hints looking at some 10X data our lab has also generated (as it seems that dropEST has been mostly tested and benchmarked on 10X and inDrop data so I figured if I could get my files into a similar format it should work ok):

K00208:217:HVK7YBBXX:3:2114:5944:43796	272	1	3014845	1	15M91495N86M	*	0	0	TCCCCCTTTTTGGCCCTGGAGTTCCCCGGTACTGGGGCATATAAAGTTTGCAAGGCCAATGGGCCTCTCTTTCCAGTGATGGCCAACTAGGCCATCTTTTG	))A--7-7-))-)--7-A7-77))))<-FAJFAFJAA<--A7-A-7<7<<7-A7-F-A-FF7-7-7-7----F7JJFF<JF7-FA<7FFF7--<-<F-7<-	NH:i:4	HI:i:2	AS:i:93	nM:i:2	RE:A:I	BC:Z:GTTTATCT	QT:Z:A-A<FAFJ	CR:Z:CCAGCGACACACAGAG	**CY:Z:AAFFFJJJJJJJJJJJ**	CB:Z:CCAGCGACACACAGAG-1	UR:Z:TTGAGAGACT	**UY:Z:FFJJJJJJJJ**	UB:Z:TTGAGAGACT	RG:Z:1:HVK7YBBXX:3
K00208:217:HVK7YBBXX:2:1212:15970:23083	272	1	3014899	1	11S89M1S	*	0	0	AAGGCAGCGTCTCCAATGGGCCTCTATTTGCATGGATGGCCGACTAGGCCATCTTTTGATACATATGTAGCTATTGTCTAGAGATCAGGGGTACTTGTTAC	7)-)-)<)7---7--))-)-7------------)7))-7)-<-7-)-)--7--FF-F-7-----7-A--<777---77-7----7-----AJ7----<7<-	NH:i:3	HI:i:3	AS:i:67	nM:i:10	RE:A:I	BC:Z:AGGCCCGA	QT:Z:-AAAFAF<	CR:Z:TTATGCTCAGCGTAAG	**CY:Z:AAFFFJJFJJJJJJJJ**	CB:Z:TTATGCTCAGCGTAAG-1	UR:Z:TCCTCGCCTT	**UY:Z:JFFJJJJJJ**J	UB:Z:TCCTCGCCTT	RG:Z:1:HVK7YBBXX:2

If we look here (https://support.10xgenomics.com/single-cell-gene-expression/software/pipelines/latest/output/bam) to see what these various bam tags refer to, and also at the general config_desc.xml file for dropEST (https://github.com/hms-dbmi/dropEst/blob/master/configs/config_desc.xml) we will see that there are two arguments that look important (however 10x uses CY and UY as noted in their page):

<cb_quality>**CQ**</cb_quality> 
<umi_quality>**UQ**</umi_quality> 

These are both found in the 10X bam files (however as CY and UY), but not in the DropSeq tools bam files. There is something with the "UQ" tag in the DropSeq tools, but it is an integer not a string and summarizes the quality of the entire UMI whereas I believe dropEST requires base-wise quality scores for both the UMI and cell barcodes.

I then wrote a script to add these tags to my own bam file (I use CQ and MQ, because UQ is already taken by DropSeq Tools) I get the following which works with dropEST:

YAP050_2_1104_1_001605021	16	10	3102131	1	2S24M	*	0	0	AAACTTATCCAGGAAAAGCACTGGGG	--<JJFFAAJAA77777<AAFFA<<<	XC:Z:GGCCGTTTCGCG	MD:Z:24	XF:Z:INTERGENIC	PG:Z:STAR	RG:Z:A	NH:i:4	NM:i:0	XM:Z:CTCCAGGC	ZP:i:27	**CQ:Z:AAAFFFJJJJJJ**	**MQ:Z:JJJJJJJJ**	UQ:i:0	AS:i:23
YAP050_2_2204_1_001398069	16	10	3102974	1	68S33M	*	0	0	ATTTTCCTCTTTGGAGCTGACTGGTGGTTATTAAGGGTGGAATGGTTATTTTCAGGAAAGTTATGGCTGTTGATAGTGGTGTCTTGGTTTCTGGAATAAGC	<A<JAF<F7-A)JJJF7<JF77-7<---A7-AAFJAAFAFFA<A7-<-7--<JJJJJFJA7<FF7A7-7--FA<FAFA7JJJFFFJF<AJJJJJFF-<<<A	XC:Z:AGTACCTCAGAC	MD:Z:33	XF:Z:INTERGENIC	PG:Z:STAR	RG:Z:A	NH:i:3	NM:i:0	XM:Z:TTCAACGG	**CQ:Z:AAA<AJFJFJFF**	**MQ:Z:7AAJ7AJJ**	UQ:i:0	AS:i:32
YAP050_2_1204_1_001062862	16	10	3103714	3	66S35M	*	0	0	GGATTAAAGGCGTGCACCACCACCACCTGGCCCATCAAACTTCTGAACGCAGTGAGAAAAAAACCACAGGCAATCAAAAGGAATGAACTGCAGAAGTTTAG	--A<7<7))-7-)7))))))7))-)7-)))7AFA-AF-F777-7-7))--A7-A-FFF<J<A7-7-<J7JAF7--FF-JJJJAA<JJ7--FFFJAFA-<<A	XC:Z:GAATAATCAGGC	MD:Z:23T11	XF:Z:INTERGENIC	PG:Z:STAR	RG:Z:A	NH:i:2	NM:i:1	XM:Z:GCTGGGGG	**CQ:Z:AAFFFJJJJJJJ**	**MQ:Z:JJJJJJJJ**	UQ:i:12	AS:i:32

Best,
Doug

**Comment by DRLaks** [comment]
Hello Doug,  
     Thanks for the elaboration.  I changed the config script to:
<cb_quality> </cb_quality>
<umi_quality> </umi_quality> 
and I think it's working now. 
All the best,
        Dan

**Comment by VPetukhov** [comment]
@darneson , thanks for the detailed explanation!

Indeed, UMI and barcode quality are optional for dropEst. If you provide some non-existing tags, the pipeline will work fine unless you run UMI correction in `dropestr`. which requires quality information. Have to admit, this part is quite non-transparent.
