### ISSUE TITLE
Cannot run UMI errors correction using reads_per_umi_per_cell from dropEst

### ISSUE THREAD

**Issue by zh542370159** [hms-dbmi/dropEst#36]
When running CorrectUmiSequenceErrors function, it occurs error 
```
Estimating prior error probabilities...
Error in CorrectUmiSequenceErrorsBayesian(reads.per.umi.per.cb, adj.umi.num = adj.umi.num,  : 
  Information about quality is required for UMI correction
```
It seems that format of  reads_per_umi_per_cell is different from the example data "reads_per_umi_per_cell" in umi-correction vignette.
I tried to modify the format but failed to make the function work.
What can i do excluding run dropEst with "-u" ?

**Comment by VPetukhov** [comment]
Did you run droptag with `-s` option?

**Comment by zh542370159** [comment]
My data is from 10x. So I directly run dropEst using .bam file as input which is from cellranger.
Following is the parament for dropEst.
`dropest -f -w -V -L eiEIBA -G 500 -g $gtf -C 21000 -c $config_file ./*.bam`

**Comment by VPetukhov** [comment]
Can you please double-check that UMI quality tag, specified in the config.xml (see config_desc.xml) is the same as tag in your bam files?

**Comment by zh542370159** [comment]
You are right. 
BAM quality tags from Cellranger are different from the default tag in 10x.xml.
Cellular barcode read quality and molecular barcode read quality is **CY** and **UY** instead of **CQ** and **UQ** .
