### ISSUE TITLE
cmake .. && make error

### ISSUE THREAD

**Issue by levinyi** [hms-dbmi/dropEst#39]
when I type  “cmake .. && make” ,errors show below, help....

-- Boost version: 1.60.0
-- Found the following Boost libraries:
--   filesystem
--   iostreams
--   log
--   system
--   thread
--   unit_test_framework
--   regex
--   date_time
--   log_setup
--   chrono
--   atomic
-- ** Boost Include: /usr/local/include
-- ** Boost Libraries: /usr/local/lib
-- ** Boost Link-Libs: /usr/local/lib/libboost_filesystem.so;/usr/local/lib/libboost_iostreams.a;/usr/local/lib/libboost_log.so;/usr/local/lib/libboost_system.so;/usr/local/lib/libboost_thread.so;/usr/local/lib/libboost_unit_test_framework.so;/usr/local/lib/libboost_regex.so;/usr/local/lib/libboost_date_time.so;/usr/local/lib/libboost_log_setup.so;/usr/local/lib/libboost_chrono.so;/usr/local/lib/libboost_atomic.so
-- Could not find libR shared library.
CMake Error at /usr/local/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find R (missing: R_LIBRARIES)
Call Stack (most recent call first):
  /usr/local/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  CMake/FindR.cmake:136 (find_package_handle_standard_args)
  CMake/deps.cmake:34 (find_package)
  CMakeLists.txt:18 (include)

-- Configuring incomplete, errors occurred!

**Comment by levinyi** [comment]
I have already installed R in /usr/local/bin/R
```
$ which R
/usr/local/bin/R

```

**Comment by VPetukhov** [comment]
Can you please check if you have `libR.so` in one of your R directories? CMake uses command `R --slave --no-save -e "cat(R.home('lib'))"` to locate this library. What's the output of the following code?
```bash
R --slave --no-save -e "cat(R.home('lib'))"
ls -la `R --slave --no-save -e "cat(R.home('lib'))"`/libR*
```

**Comment by levinyi** [comment]
hi，really thanks for your reply, I'm trying to reinstall R with `./configure --enable-R-shlib` , now it's work. but there is a new issue,
when I type cmake ..  ,it's done without any error, see below:
```
-- Configuring done
-- Generating done
-- Build files have been written to: /home/XXX/dropEst/build
```
But when I type 'make', it shows ;
```
[ 11%] Built target DropTools
[ 31%] Built target TagsSearch
[ 33%] Linking CXX executable droptag
/usr/bin/ld: /usr/local/lib64/R/lib/libR.so: undefined reference to symbol 'inflateEnd'
/usr/local/lib/libz.so.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [droptag] Error 1
make[1]: *** [CMakeFiles/droptag.dir/all] Error 2
make: *** [all] Error 2
```
I don't know how to solve it,please help.

**Comment by VPetukhov** [comment]
Sorry for the late response, but did you find a solution?

**Comment by levinyi** [comment]
yes, It's done.  reinstall libz ?  sorry I forgot...

**Comment by VPetukhov** [comment]
Great, so I'm closing the issue.

**Comment by levinyi** [comment]
sorry，

**Comment by levinyi** [comment]
hi,I have a problem again.
`
cmake -DBAMTOOLS_ROOT=/BIGDATA1/cygene_sydu_1/local/usr/local -DR_ROOT=/BIGDATA1/app/R/3.4.3-gcc-4.8.5/lib64/R/lib ..
`

```
-- Could not find libR shared library.
CMake Error at /BIGDATA1/app/cmake/3.10.1-gcc-4.8.5/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find R (missing: R_LIBRARIES)
Call Stack (most recent call first):
  /BIGDATA1/app/cmake/3.10.1-gcc-4.8.5/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  CMake/FindR.cmake:136 (find_package_handle_standard_args)
  CMake/deps.cmake:34 (find_package)
  CMakeLists.txt:18 (include)
```

but I type` ls -la `R --slave --no-save -e "cat(R.home('lib'))"`/libR*` the libR is here.
```
ls -la `R --slave --no-save -e "cat(R.home('lib'))"`/libR*
-rwxr-xr-x 1 nscc_ts_1 nscc_ts  444152 Feb  9  2018 /BIGDATA1/app/R/3.4.3-gcc-4.8.5/lib64/R/lib/libRblas.so
-rwxr-xr-x 1 nscc_ts_1 nscc_ts 5262352 Feb  9  2018 /BIGDATA1/app/R/3.4.3-gcc-4.8.5/lib64/R/lib/libRlapack.so

```
do I use the wrong command?
