### ISSUE TITLE
Could NOT find BAMTOOLS

### ISSUE THREAD

**Issue by DadongZ** [hms-dbmi/dropEst#4]
I got below issues when trying to install the pipeline:

```
~/dropEst$ cmake . && make
-- Boost version: 1.55.0
-- Found the following Boost libraries:
--   unit_test_framework
--   thread
--   system
--   log
--   iostreams
--   filesystem
--   chrono
--   date_time
--   atomic
--   log_setup
--   regex
-- Could NOT find BAMTOOLS (missing: BAMTOOLS_LIBRARY BAMTOOLS_INCLUDE_DIR) 
-- Found R: /usr/lib/R
-- Configuring done
CMake Error: Unable to open check cache file for write. /home/dz33/dropEst/CMakeFiles/cmake.check_cache
```

The bamtools have bee installed in:
```
:~/dropEst$ which bamtools
/usr/bin/bamtools
```

Any suggestions? Thanks

**Comment by VPetukhov** [comment]
It looks like you have bamtools executable, but not C++ library. On some linux distributions they are located in separate packages. For instance, Ubuntu has `bamtools` for binary executable and `libbamtools-dev` for library. Please, ensure that proper version is installed. If you don't have superuser access, please install it locally by [the instruction](https://github.com/pezmaster31/bamtools/wiki/Building-and-installing).

**Comment by pkharchenko** [comment]
I've encountered similar error on ada. cmake finished without any warnings. However, compilation failed on 
[ 13%] Building CXX object CMakeFiles/Estimation.dir/Estimation/CellsDataContainer.cpp.o
/home/pkharchenko/dropEst/Estimation/CellsDataContainer.cpp:9:32: fatal error: api/BamMultiReader.h: No such file or directory
 #include <api/BamMultiReader.h>

Seems like we should be checking for this at cmake stage, and also providing more detailed instructions on how to install bamtools with headers. I see that newer versions of Unbuntu have libbamtools-dev.
