### ISSUE TITLE
dropest error

### ISSUE THREAD

**Issue by levinyi** [hms-dbmi/dropEst#43]
my command is 
`/dropest -w -m -r sample8.params.gz sample7.params.gz sample6.params.gz sample5.params.gz sample4.params.gz sample3.params.gz sample2.params.gz sample1.params.gz -g /home/dushiyi/database/refdata-cellranger-GRCh38-1.2.0/genes/genes.gtf -c /cygene/work/02.dropEst/10x.test.xml ../02_alignment/Aligned.out.bam
`
while the output is :
```
../02_alignment/Aligned.out.bam: 400000000 total reads; 14.9% intergenic; 65.1% touch exon; 12.4% touch intron; 0.489% touch not annotated regions; can't parse 0.0792053% reads; 7678441 CBs read
../02_alignment/Aligned.out.bam: 410000000 total reads; 14.9% intergenic; 65.1% touch exon; 12.4% touch intron; 0.487% touch not annotated regions; can't parse 0.078822% reads; 7874334 CBs read
WARNING: Can't find chromosome 'KI270510.1'
../02_alignment/Aligned.out.bam: 420000000 total reads; 14.9% intergenic; 65.1% touch exon; 12.4% touch intron; 0.485% touch not annotated regions; can't parse 0.0784669% reads; 8050887 CBs read
../02_alignment/Aligned.out.bam: 430000000 total reads; 14.9% intergenic; 65.1% touch exon; 12.4% touch intron; 0.483% touch not annotated regions; can't parse 0.078086% reads; 8214251 CBs read
../02_alignment/Aligned.out.bam: 440000000 total reads; 14.9% intergenic; 65.1% touch exon; 12.4% touch intron; 0.481% touch not annotated regions; can't parse 0.0777873% reads; 8365859 CBs read
std::bad_alloc

```

and the result is 
```
$ cat cell.counts.mtx
%%MatrixMarket matrix coordinate pattern symmetric
0 0 0
```
what's wrong with me? The step1 `dropTag` and step 2 `alignment` are all correct.

**Comment by levinyi** [comment]
maybe because out of memory, so, any parameter can limit mem ?

**Comment by VPetukhov** [comment]
Yes, out of memory error explains the issue. At least, I don't see any other reasons. 

> any parameter can limit mem ?

The pipeline need to read all bam files in memory. I don't see the way to change the logic without terrible loss in either performance or functionality. Though if you have any suggestion, I'd be glad to discuss.
