### ISSUE TITLE
cmake error: Could not find the following Boost libraries

### ISSUE THREAD

**Issue by levinyi** [hms-dbmi/dropEst#44]
hi,
I had some errors with boost :
```
cmake  -DBAMTOOLS_ROOT=/BIGDATA1/cygene_sydu_1/local/usr/local  -DBOOST_ROOT=/BIGDATA1/cygene_sydu_1/local  ..
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
CMake Error at /BIGDATA1/app/cmake/3.10.1-gcc-4.8.5/share/cmake-3.10/Modules/FindBoost.cmake:1928 (message):
  Unable to find the requested Boost libraries.

  Boost version: 1.60.0

  Boost include path: /BIGDATA1/cygene_sydu_1/local/include

  Could not find the following Boost libraries:

          boost_filesystem
          boost_log
          boost_system
          boost_thread
          boost_unit_test_framework

  Some (but not all) of the required Boost libraries were found.  You may
  need to install these additional Boost libraries.  Alternatively, set
  BOOST_LIBRARYDIR to the directory containing Boost libraries or BOOST_ROOT
  to the location of Boost.
Call Stack (most recent call first):
  CMake/deps.cmake:19 (find_package)
  CMakeLists.txt:18 (include)


-- Found ZLIB: /usr/lib64/libz.so (found version "1.2.7")
-- Found BAMTOOLS: /BIGDATA1/cygene_sydu_1/local/usr/local/bin/../lib64/libbamtools.a
-- Found R: /BIGDATA1/cygene_sydu_1/R/3.4/lib64/R/lib/libR.so
-- Found R: /BIGDATA1/cygene_sydu_1/R/3.4/lib64/R
-- Configuring incomplete, errors occurred!
See also "/BIGDATA1/cygene_sydu_1/software/dropEst-master/build/CMakeFiles/CMakeOutput.log".
See also "/BIGDATA1/cygene_sydu_1/software/dropEst-master/build/CMakeFiles/CMakeError.log".
```

I install boost followed by the user's guide like this :
```
./bootstrap.sh --with-libraries=filesystem,iostreams,log,system,thread,test
./b2 cxxflags="-std=c++11" include="$LOCAL_LIBS/include/" search="$LOCAL_LIBS/lib/" link=shared threading=multi install --prefix=$LOCAL_LIBS
```

anyone helps? Thanks!

**Comment by levinyi** [comment]
> hi,
> I had some errors with boost :
> 
> ```
> cmake  -DBAMTOOLS_ROOT=/BIGDATA1/cygene_sydu_1/local/usr/local  -DBOOST_ROOT=/BIGDATA1/cygene_sydu_1/local  ..
> -- The C compiler identification is GNU 4.8.5
> -- The CXX compiler identification is GNU 4.8.5
> -- Check for working C compiler: /usr/bin/cc
> -- Check for working C compiler: /usr/bin/cc -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Check for working CXX compiler: /usr/bin/c++
> -- Check for working CXX compiler: /usr/bin/c++ -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- Looking for pthread.h
> -- Looking for pthread.h - found
> -- Looking for pthread_create
> -- Looking for pthread_create - not found
> -- Looking for pthread_create in pthreads
> -- Looking for pthread_create in pthreads - not found
> -- Looking for pthread_create in pthread
> -- Looking for pthread_create in pthread - found
> -- Found Threads: TRUE
> CMake Error at /BIGDATA1/app/cmake/3.10.1-gcc-4.8.5/share/cmake-3.10/Modules/FindBoost.cmake:1928 (message):
>   Unable to find the requested Boost libraries.
> 
>   Boost version: 1.60.0
> 
>   Boost include path: /BIGDATA1/cygene_sydu_1/local/include
> 
>   Could not find the following Boost libraries:
> 
>           boost_filesystem
>           boost_log
>           boost_system
>           boost_thread
>           boost_unit_test_framework
> 
>   Some (but not all) of the required Boost libraries were found.  You may
>   need to install these additional Boost libraries.  Alternatively, set
>   BOOST_LIBRARYDIR to the directory containing Boost libraries or BOOST_ROOT
>   to the location of Boost.
> Call Stack (most recent call first):
>   CMake/deps.cmake:19 (find_package)
>   CMakeLists.txt:18 (include)
> 
> 
> -- Found ZLIB: /usr/lib64/libz.so (found version "1.2.7")
> -- Found BAMTOOLS: /BIGDATA1/cygene_sydu_1/local/usr/local/bin/../lib64/libbamtools.a
> -- Found R: /BIGDATA1/cygene_sydu_1/R/3.4/lib64/R/lib/libR.so
> -- Found R: /BIGDATA1/cygene_sydu_1/R/3.4/lib64/R
> -- Configuring incomplete, errors occurred!
> See also "/BIGDATA1/cygene_sydu_1/software/dropEst-master/build/CMakeFiles/CMakeOutput.log".
> See also "/BIGDATA1/cygene_sydu_1/software/dropEst-master/build/CMakeFiles/CMakeError.log".
> ```
> I install boost followed by the user's guide like this :
> 
> ```
> ./bootstrap.sh --with-libraries=filesystem,iostreams,log,system,thread,test
> ./b2 cxxflags="-std=c++11" include="$LOCAL_LIBS/include/" search="$LOCAL_LIBS/lib/" link=shared threading=multi install --prefix=$LOCAL_LIBS
> ```
> anyone helps? Thanks!

**Comment by shaaaarpy** [comment]
Hey 
I have the same error. How did you resolve this?

Thank you

**Comment by VPetukhov** [comment]
Did you look at [troubleshooting](https://dropest.readthedocs.io/en/latest/setup.html#troubleshooting) page?
