### ISSUE TITLE
Issue in filtration and QC/ making figures (e.g. fig 4 in paper)

### ISSUE THREAD

**Issue by KhadeejaSiddique** [hms-dbmi/dropEst#50]
I have now these following files after running dropest pipeline.. 
1. cell.count.rds
2. cell.counts.matrices.rds
3. cell.count.cells.tsv
4. cell.counts.genes.tsv
5.  cell.count.mtx files
I am interested in having a comparison between dropEst and cellRanger. I am trying to make figures  but I am not getting how to make it. I also want to do filtration and QC. I am following this links but still unable to do.  Which file should I use? 

https://github.com/VPetukhov/dropEstAnalysis
https://github.com/hms-dbmi/dropEst/tree/master/dropestr/vignettes

I am looking forward to.

**Comment by VPetukhov** [comment]
To reproduce Fig. 4 you need to use [this file](vpetukhov.github.io/dropEstAnalysis/low_quality_cells__validation_bmmc1.html). [Here](vpetukhov.github.io/dropEstAnalysis/) you can find section "Content by figures", which will help you to find proper files.
