### ISSUE TITLE
FillCollisionsAdjustmentInfo is taking too long to complete

### ISSUE THREAD

**Issue by k3yavi** [hms-dbmi/dropEst#51]
Hi @VPetukhov ,
I am trying to use DropEst with one of the 10x datasets from [here](https://support.10xgenomics.com/single-cell-gene-expression/datasets/2.1.0/neurons_900).
I downloaded the BAM from the above link and used `dropest -f` mode to generate the count matrix and the `rds` file for the downstream UMI correction. Unfortunately I am noob in R and just copy pasting code from [this](https://github.com/hms-dbmi/dropEst/blob/master/dropestr/vignettes/umi-correction.Rmd) tutorial. I have got a couple of question regarding the working of dropEst pipeline:
1. When we provide an external BAM (like from 10x website in my case) what type of UMI correction does `dropest` command do before generating the count matrix? I am guessing it simply count the tags from the BAM if I don't give either `-m` or `-M`?
2. When I try to use `dropestr` R package following the above tutorial it seems to give good umi distribution till [here](https://github.com/hms-dbmi/dropEst/blob/master/dropestr/vignettes/umi-correction.Rmd). But once I try to use the function 
```
collisions_info <- FillCollisionsAdjustmentInfo(umi_probabilities, max_umi_per_gene, step=20, mc.cores=5, verbose=T)
```
the program give following error
```
> FillCollisionsAdjustmentInfo(umi_probabilities, max_umi_per_gene, step=20, mc.cores=5, verbose=T)
Error in FillCollisionsAdjustmentInfo(umi_probabilities, max_umi_per_gene,  :
  unused arguments (step = 20, mc.cores = 5, verbose = T)
```
So I removed `step = 20, mc.cores = 5, verbose = T` but it has been 3 days now and the program won't finish.

What am I doing wrong? Thanks again for your help.

my `config.xml`
```
<config>
    <!-- droptag -->
    <TagsSearch>
        <protocol>10x</protocol>
        <BarcodesSearch>
            <barcode1_length>8</barcode1_length>
            <barcode2_length>16</barcode2_length>
            <umi_length>10</umi_length>
            <r1_rc_length>0</r1_rc_length>
        </BarcodesSearch>

        <Processing>
            <min_align_length>10</min_align_length>
            <reads_per_out_file>10000000</reads_per_out_file>
            <poly_a_tail>AAAAAAAA</poly_a_tail>
        </Processing>
    </TagsSearch>

    <!-- dropest -->
    <Estimation>
        <Merge>
	    <barcodes_file>/mnt/scratch5/avi/dropest_data/barcodes.tsv</barcodes_file>
            <barcodes_type>const</barcodes_type>
            <min_merge_fraction>0.2</min_merge_fraction>
            <max_cb_merge_edit_distance>2</max_cb_merge_edit_distance>
            <max_umi_merge_edit_distance>1</max_umi_merge_edit_distance>
            <min_genes_after_merge>100</min_genes_after_merge>
            <min_genes_before_merge>20</min_genes_before_merge>
        </Merge>

        <PreciseMerge>
            <max_merge_prob>1e-5</max_merge_prob>
            <max_real_merge_prob>1e-7</max_real_merge_prob>
        </PreciseMerge>
    </Estimation>

    <BamTags> <!-- Optional. Tags, which are used to parse .bam file (-f option) or to print tagged .bam file (-b or -F options). Default values correspond to 10x protocol. -->
        <cb>CB</cb> <!-- Cell barcode. Default: CB. -->
        <cb_raw>CR</cb_raw> <!-- Cell barcode raw. Used only for bam output. Default: CR. -->
        <umi>UB</umi> <!-- UMI. Default: UB. -->
        <umi_raw>UR</umi_raw> <!-- UMI raw. Used only for bam output. Default: UR. -->
        <gene>GX</gene> <!-- Gene id. Default: GX. -->
        <cb_quality>CQ</cb_quality> <!-- Cell barcode quality. Default: CQ. -->
        <umi_quality>UQ</umi_quality> <!-- UMI quality. Default: UQ. -->
    </BamTags>
</config>

```

**Comment by k3yavi** [comment]
Hi @VPetukhov ,
The experiment have the following numbers:
```
> max_umi_per_gene
[1] 4192617
> length(umi_probabilities)
[1] 1048576
```

**Comment by VPetukhov** [comment]
4 millions UMIs per gene? It's definitely not a correct number. Can you please publish your dropEst log?

**Comment by k3yavi** [comment]
Unfortunately I can't find the log of the run, but I just used the bam from the 10x website and the config as attached above.
Attaching the results.html file.

[report.html.zip](https://github.com/hms-dbmi/dropEst/files/2590783/report.html.zip)

**Comment by VPetukhov** [comment]
There were several problems with UMI correction, but now it should work. Please, check [the result](http://pklab.med.harvard.edu/viktor/dropest_paper/dropest_0.8.5.zip) I published for neurons_900. I fixed your config, so the pipeline reads non-corrected UMI and their quality.

**Comment by k3yavi** [comment]
Thanks @VPetukhov for looking into it, I'll try running the tool again and report back.

**Comment by k3yavi** [comment]
@VPetukhov ,
With the latest version of dropEst, I get the following error.
```
/mnt/scratch5/avi/alevin/bin/dropest/dropEst/build/dropest -f -c est_config.dump.xml -C 1200 ./possorted_genome_bam.bam
Version: 0.8.5.
Run: 02/02/2019 16:27:07.
No such node (max_cb_merge_edit_distance)
```

I am using the same `xml` file as you shared for the `neurons_900` dataset in https://github.com/hms-dbmi/dropEst/issues/68 and got the bam from the 10x website.

The weirdest thing is that, with every run of drpoEst, `xml` file gets cleared out. I double checked for the content of the `xml` file before giving that as an input to dropEst, but the program fails with the above error.

Thanks in advance for your help.

**Comment by k3yavi** [comment]
I can use `dropestr` to generate UMI corrected counts now.
Thanks for the help.

**Comment by evanbiederstedt** [comment]
Hey @k3yavi 

If you could provide more information so this could be debugged, I would appreciate it. 

Thanks, Evan
