### ISSUE TITLE
Error with dropEst

### ISSUE THREAD

**Issue by chlee-tabin** [hms-dbmi/dropEst#52]
The following run (log):

```
cat est_main.log
/home/cl266/dropEst/dropest -m -V -r drop/dlib27.FC04320.L001.params.gz drop/dlib27.FC04320.L002.params.gz drop/dlib27.FC04320.L003.params.gz drop/dlib27.FC04320.L004.params.gz -g drop.reference.wo.pseudo/mm10.with.compact.transgenes.filtered.20180315.gtf -o drop/dlib27.out/cell.counts.bcconfig.rds -c /home/cl266/dropEst/configs/indrop_v3_with_barcodes.xml drop/dlib27.out/Aligned.out.sorted.bam 
Version: 0.8.3.
```

produces this immediate error:
```
Error in intToUtf8(8216) : 
  3 arguments passed to .Internal(intToUtf8) which requires 2
In addition: Warning message:
package "methods" in options("defaultPackages") was not found 
Error in sort.int(x, na.last = na.last, decreasing = decreasing, ...) : 
  there is no .Internal function 'sorted_fpass'
Fatal error: unable to initialize the JIT
```

I am wondering whether it had to do with updating the R to 3.5.1. I tried to do all package updates but produces the same error. Would there by a workaround?

**Comment by szimmerman92** [comment]
I just got this error as well when I installed dopEst with R 3.2.5 and tried to use it with R 3.5.1. When I re-installed dropEst with R version 3.5.1 the issue was fixed.

**Comment by chlee-tabin** [comment]
I reverted back to R 3.4.1, re-installed all R packages to a local library clean, and re-built dropEst, everything worked fine! Thank you!
