### ISSUE TITLE
errors when doing dropEst cmake. Help!!!

### ISSUE THREAD

**Issue by Jun-NIBS** [hms-dbmi/dropEst#54]
CMake Error at /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find R (missing: RINSIDE_INCLUDE_DIR RINSIDE_LIBRARY)
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  CMake/FindR.cmake:136 (find_package_handle_standard_args)
  CMake/deps.cmake:34 (find_package)
  CMakeLists.txt:18 (include)

-- Configuring incomplete, errors occurred!

**Comment by Jun-NIBS** [comment]
Is it the R package Rlnside? if it is, I have installed.

**Comment by Jun-NIBS** [comment]
My version is 0.2.14

**Comment by VPetukhov** [comment]
Yes, it is. Can you please, publish the whole CMake log?

**Comment by Jun-NIBS** [comment]
u2510@GenekServer-0:~/github/dropEst/build/CMakeFiles$ cat CMakeError.log
Determining if the pthread_create exist failed with the following output:
Change Dir: /home/u2510/github/dropEst/build/CMakeFiles/CMakeTmp

Run Build Command:"/pub/anaconda3/bin/make" "cmTC_87d9c/fast"
/pub/anaconda3/bin/make -f CMakeFiles/cmTC_87d9c.dir/build.make CMakeFiles/cmTC_87d9c.dir/build
make[1]: Entering directory '/home/u2510/github/dropEst/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_87d9c.dir/CheckSymbolExists.c.o
/usr/bin/cc     -o CMakeFiles/cmTC_87d9c.dir/CheckSymbolExists.c.o   -c /home/u2510/github/dropEst/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c
Linking C executable cmTC_87d9c
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_87d9c.dir/link.txt --verbose=1
/usr/bin/cc       CMakeFiles/cmTC_87d9c.dir/CheckSymbolExists.c.o  -o cmTC_87d9c -rdynamic 
CMakeFiles/cmTC_87d9c.dir/CheckSymbolExists.c.o: In function `main':
CheckSymbolExists.c:(.text+0x16): undefined reference to `pthread_create'
collect2: error: ld returned 1 exit status
make[1]: *** [CMakeFiles/cmTC_87d9c.dir/build.make:98: cmTC_87d9c] Error 1
make[1]: Leaving directory '/home/u2510/github/dropEst/build/CMakeFiles/CMakeTmp'
make: *** [Makefile:126: cmTC_87d9c/fast] Error 2

File /home/u2510/github/dropEst/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c:
/* */
#include <pthread.h>

int main(int argc, char** argv)
{
  (void)argv;
#ifndef pthread_create
  return ((int*)(&pthread_create))[argc];
#else
  (void)argc;
  return 0;
#endif
}

Determining if the function pthread_create exists in the pthreads failed with the following output:
Change Dir: /home/u2510/github/dropEst/build/CMakeFiles/CMakeTmp

Run Build Command:"/pub/anaconda3/bin/make" "cmTC_da4e3/fast"
/pub/anaconda3/bin/make -f CMakeFiles/cmTC_da4e3.dir/build.make CMakeFiles/cmTC_da4e3.dir/build
make[1]: Entering directory '/home/u2510/github/dropEst/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_da4e3.dir/CheckFunctionExists.c.o
/usr/bin/cc    -DCHECK_FUNCTION_EXISTS=pthread_create   -o CMakeFiles/cmTC_da4e3.dir/CheckFunctionExists.c.o   -c /usr/share/cmake-3.5/Modules/CheckFunctionExists.c
Linking C executable cmTC_da4e3
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_da4e3.dir/link.txt --verbose=1
/usr/bin/cc   -DCHECK_FUNCTION_EXISTS=pthread_create    CMakeFiles/cmTC_da4e3.dir/CheckFunctionExists.c.o  -o cmTC_da4e3 -rdynamic -lpthreads 
/usr/bin/ld: cannot find -lpthreads
collect2: error: ld returned 1 exit status
make[1]: *** [CMakeFiles/cmTC_da4e3.dir/build.make:98: cmTC_da4e3] Error 1
make[1]: Leaving directory '/home/u2510/github/dropEst/build/CMakeFiles/CMakeTmp'
make: *** [Makefile:126: cmTC_da4e3/fast] Error 2

**Comment by Jun-NIBS** [comment]
this is my  CMakeError.log

**Comment by Jun-NIBS** [comment]
I don't have the root, and I don't know whether it affects cmake?

**Comment by Jun-NIBS** [comment]
Thank you for your answer!!

**Comment by Jun-NIBS** [comment]
-- Found ZLIB: /home/u2510/local/lib/libz.so (found version "1.2.11") 
-- Found BAMTOOLS: /home/u2510/local/usr/local/lib/../lib/libbamtools.a  
-- Found R: /pub/anaconda3/lib/R/lib/libR.so  
-- Found R: /pub/anaconda3/lib/R
-- Configuring done
CMake Warning at CMakeLists.txt:44 (add_executable):
  Cannot generate a safe runtime search path for target dropest because there
  is a cycle in the constraint graph:

    dir 0 is [/home/u2510/local/lib]
      dir 3 must precede it due to runtime library [libboost_iostreams.so.1.60.0]
    dir 1 is [/pub/anaconda3/lib/R/lib]
    dir 2 is [/home/u2510/R/x86_64-pc-linux-gnu-library/3.5/RInside/lib]
    dir 3 is [/pub/anaconda3/lib]
      dir 0 must precede it due to runtime library [libz.so.1]

  Some of these libraries may not be found correctly.


CMake Warning at CMakeLists.txt:68 (add_executable):
  Cannot generate a safe runtime search path for target
  TestEstimationMergeProbs because there is a cycle in the constraint graph:

    dir 0 is [/home/u2510/local/lib]
      dir 3 must precede it due to runtime library [libboost_iostreams.so.1.60.0]
    dir 1 is [/pub/anaconda3/lib/R/lib]
    dir 2 is [/home/u2510/R/x86_64-pc-linux-gnu-library/3.5/RInside/lib]
    dir 3 is [/pub/anaconda3/lib]
      dir 0 must precede it due to runtime library [libz.so.1]

  Some of these libraries may not be found correctly.


CMake Warning at CMakeLists.txt:47 (add_executable):
  Cannot generate a safe runtime search path for target filter_mixture_bam
  because there is a cycle in the constraint graph:

    dir 0 is [/home/u2510/local/lib]
      dir 3 must precede it due to runtime library [libboost_iostreams.so.1.60.0]
    dir 1 is [/pub/anaconda3/lib/R/lib]
    dir 2 is [/home/u2510/R/x86_64-pc-linux-gnu-library/3.5/RInside/lib]
    dir 3 is [/pub/anaconda3/lib]
      dir 0 must precede it due to runtime library [libz.so.1]

  Some of these libraries may not be found correctly.


CMake Warning at CMakeLists.txt:63 (add_executable):
  Cannot generate a safe runtime search path for target TestEstimation
  because there is a cycle in the constraint graph:

    dir 0 is [/home/u2510/local/lib]
      dir 3 must precede it due to runtime library [libboost_iostreams.so.1.60.0]
    dir 1 is [/pub/anaconda3/lib/R/lib]
    dir 2 is [/home/u2510/R/x86_64-pc-linux-gnu-library/3.5/RInside/lib]
    dir 3 is [/pub/anaconda3/lib]
      dir 0 must precede it due to runtime library [libz.so.1]

  Some of these libraries may not be found correctly.


-- Generating done
-- Build files have been written to: /home/u2510/github/dropEst/build

Does this mean it works?

**Comment by VPetukhov** [comment]
You definitely have some problems with library paths. When you have normal libraries installed together with anaconda, they start conflicting with each other, because cmake can find some of them, while linker tries to link to the other and so on. There is no universal solution except trying to minimize number of software, installed with conda by building it from sources by hands. Sorry, but there is not much help I can provide.

**Comment by Jun-NIBS** [comment]
Thanks!!!
I’ll try.

Best
Jun


发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: Viktor Petukhov <notifications@github.com>
发送时间: Friday, November 16, 2018 7:16:20 PM
收件人: hms-dbmi/dropEst
抄送: Jun; Author
主题: Re: [hms-dbmi/dropEst] errors when doing dropEst cmake. Help!!! (#54)


You definitely have some problems with library paths. When you have normal libraries installed together with anaconda, they start conflicting with each other, because cmake can find some of them, while linker tries to link to the other and so on. There is no universal solution except trying to minimize number of software, installed with conda by building it from sources by hands. Sorry, but there is not much help I can provide.

―
