### ISSUE TITLE
dropTag filtering out all reads

### ISSUE THREAD

**Issue by bradbal** [hms-dbmi/dropEst#55]
Hi,
The results from dropTag appear to suggest none of the reads pass some quality threshold.
I have performed fastqc on all of my data and ran dropTag with the highest quality fastq files.
Droptag still filtered out all the reads.

I am not completely sure on the scRNA-seq protocols, except that I am quite sure it is
inDrop. Hopefully I will hear back from the wetlab with more details soon. 
I have tried with the R1 and R2 the other way around as well and still get the
same result. 

Any help on this would be greatly appreciated. I am currently reading the umi-tools documentation to see if I can perform similar functionality to dropTag. 

I ran:

droptag -c /home/dropEst/configs/indrop_v1_2.xml -s -S -p 20 
./mergedDir/F4499/F4499_R1.fastq.gz ./mergedDir/F4499/F4499_R2.fastq.gz 

My dropTag stderr output was:
Version: 0.8.3.
Run: 10:41:33.
Total 5000000 read (0 parsed, 0 passed quality threshold)
Total 10000000 read (0 parsed, 0 passed quality threshold)
Total 15000000 read (0 parsed, 0 passed quality threshold)
Total 20000000 read (0 parsed, 0 passed quality threshold)
Total 25000000 read (0 parsed, 0 passed quality threshold)
Total 30000000 read (0 parsed, 0 passed quality threshold)
Total 35000000 read (0 parsed, 0 passed quality threshold)
Total 40000000 read (0 parsed, 0 passed quality threshold)
Total 45000000 read (0 parsed, 0 passed quality threshold)
Total 50000000 read (0 parsed, 0 passed quality threshold)
Total 55000000 read (0 parsed, 0 passed quality threshold)
Total 60000000 read (0 parsed, 0 passed quality threshold)
 (62590751 reads)
Outcomes:
[ (OK)  (No spacer)  (Short)  (Spacer modified) ]
[0 62590751 0 0 ]
[0 100 0 0 ] %

	Trim stat:
[ (no trim)  (RC)  (PolyA)  (-A) ]
[0 0 0 0 ]
[-nan -nan -nan -nan ] %

Reading completed: 10:49:13.
Writing the rest lines
All done: 10:49:13.
Writing R data to F4499_R2.fastq.gz.tagged.rds: 10:49:13.

**Comment by bradbal** [comment]
While this is still an issue, note that I have gotten around this by using umi_tools.

**Comment by chenyang91316** [comment]
Dear sir
I have also get the same problem. Could anyone give me some advice?
