### ISSUE TITLE
Difference between cm_raw and cm

### ISSUE THREAD

**Issue by chlee-tabin** [hms-dbmi/dropEst#56]
Hi,

I was having a hard time of finding what the difference between `cm_raw` and `cm` is. I believe the `cm_raw` contains the matrix before UMI correction and `cm` is after UMI correction?

In some of the examples of filtration, for example, [this](https://vpetukhov.github.io/dropEstAnalysis/low_quality_cells__validation_pbmc8k.html), the total UMI count for a given droplet was calculated explicitly from the `cm_raw` slot. What is the reasoning behind this?

Just when I plot the total UMI counts between `cm_raw` and `cm`, I observe this:
![image](https://user-images.githubusercontent.com/31305155/48455630-f0b91f80-e789-11e8-9ad7-62e9f5ebb6d1.png)

Is it normally the case that the total count of `cm` is higher than `cm_raw`? (My platform is indrop v3, and I used the -u option to do directional UMI correction when running `dropEst`)

**Comment by chlee-tabin** [comment]
P.S. I also see that some cellular barcodes are missing in `cm` (so the columns) than `cm_raw`, although some have definitely get good quality scores and also have decent UMI counts (from `cm_raw`). Is this a result of merging cellular barcodes?

**Comment by VPetukhov** [comment]
Hi,

First, `cm_raw` has weaker filtration by number of genes, and second it has all types of UMIs (see part [Count intronic / exonic reads only](https://github.com/hms-dbmi/dropEst#count-intronic--exonic-reads-only)), which means `-L eEiIBA`. This matrix is stored for low-quality cell filtration, as there we don't care about read types and also we need examples of low-quality cells.

**Comment by chlee-tabin** [comment]
Thank you very much!

So if I understand correctly, `cm_raw` contains cells that have at least 20 genes and have been merged or due to poor quality of cellular barcode sequence excluded, whereas `cm` contains cells that were further filtered to at least have 100 genes (default, changeable by `-G` option).

I also realize that the total number of UMI count plot above was reversed, as you say, due to the inclusion of intronic sequences the `cm_raw` has **higher** number of totals than `cm` (the labeling is reversed).

**Comment by VPetukhov** [comment]
@chlee-tabin , small correction: `cm` still can (and most probably will) contain some poor quality cells. It's filtered only by `-G` and `-C` options. But because quality scoring is not perfect, it's up to user to decide whether to filter low-quality cells if needed. The rest is correct.

**Comment by chlee-tabin** [comment]
Oh, I was reading the dropEst log, wondering about the difference of "merged CBs" and "excluded CBs". I guessed that the excluded CBs do not have a defined CB to merge to.

**Comment by VPetukhov** [comment]
Exactly. CBs are merged it they have similar barcode and similar gene composition. But if a cell has barcode, which isn't presented in the whitelist and it has no similar cells, it's just excluded.
