### ISSUE TITLE
option to retain filtered cells?

### ISSUE THREAD

**Issue by chlee-tabin** [hms-dbmi/dropEst#57]
I wanted to estimate the contamination of ambient RNA using [SoupX](https://github.com/constantAmateur/SoupX) package. It requires to have the unfiltered cell UMI count matrices to estimate the transcriptome of the ambient RNA mix in the sample. I thought of using the `cm_raw` for this purpose, but per [this](https://github.com/hms-dbmi/dropEst/issues/56) issue, I learned that `cm_raw` has the default read mapping includes intronic reads, which can considerably inflate the UMI counts of filtered cells. Would it be possible to have an option to obtain all the `cm` with less than 100 gene counts?

**Comment by VPetukhov** [comment]
Do you mean `-G` option, like `-G 20`? It controls minimal number of gene per cell for `cm`.

**Comment by chlee-tabin** [comment]
Yes, but that option has the minimum still with 20? At least I tried with `-G 1` and it still filters cellular barcodes more than 20 genes.

**Comment by VPetukhov** [comment]
There are two stages of filtration: before merge and after it. For such low values you need to change them both. The first one is controlled by `Estimation/merge/min_genes_before_merge` parameter in the config. But please, keep in mind that reducing the threshold to extreme values such as 1, you'll get really a lot of noisy cells, which can significantly increase computation time and RAM requirements.

**Comment by chlee-tabin** [comment]
Thank you! That helped me a lot!
