### ISSUE TITLE
Running time for dropest program

### ISSUE THREAD

**Issue by lxhuang7** [hms-dbmi/dropEst#58]
Hi,

I was running dropest step on a dropseq_tools(v.2.0.0)-processed bam file (93742939 reads) on a MacOS (Mojave) machine (2.6 GHz Intel core i7, 32GB DDR4 memory). It's been over 10 hours but the job hasn't finished yet. I wondered what the typical running time for this kind of analysis. Or if I did something wrong? Is there anyway to speed this up? Thanks in advance.
-Lei

P.S.  The following is the program log file. Previously I replaced -M option to -m option from the command line and the situation didn't seem to improve much.

/usr/local/bin/dropest -M -f -G 100 -o /Users/lhuang/Documents/software/test/results/S1/counts/dropest_count -l /Users/lhuang/Documents/software/test/results/S1/counts/S1.dropest -c /Users/lhuang/Documents/software/test/reference/drop_seq.xml /Users/lhuang/Documents/software/test/results/S1/alignment/final.alt.bam
Version: 0.8.5.
Run: 11/15/2018 00:01:45.
Poisson Simple merge selected.

Start parsing of bams: 00:01:45.
/Users/lhuang/Documents/software/test/results/S1/alignment/final.alt.bam: 10000000 primarily aligned reads (7.48% intergenic, 68.7% touch exon, 10.6% touch intron, 13.2% touch both gene and not annotated regions), 0 non-mapped reads, 464047 CBs read
/Users/lhuang/Documents/software/test/results/S1/alignment/final.alt.bam: 20000000 primarily aligned reads (10.2% intergenic, 65.2% touch exon, 10.9% touch intron, 13.7% touch both gene and not annotated regions), 0 non-mapped reads, 792487 CBs read
/Users/lhuang/Documents/software/test/results/S1/alignment/final.alt.bam: 30000000 primarily aligned reads (10.6% intergenic, 64.8% touch exon, 11.1% touch intron, 13.6% touch both gene and not annotated regions), 0 non-mapped reads, 1071667 CBs read
/Users/lhuang/Documents/software/test/results/S1/alignment/final.alt.bam: 40000000 primarily aligned reads (13.7% intergenic, 63% touch exon, 10.4% touch intron, 13% touch both gene and not annotated regions), 0 non-mapped reads, 1308640 CBs read
/Users/lhuang/Documents/software/test/results/S1/alignment/final.alt.bam: 50000000 primarily aligned reads (13.2% intergenic, 62.7% touch exon, 10.5% touch intron, 13.5% touch both gene and not annotated regions), 0 non-mapped reads, 1541539 CBs read
/Users/lhuang/Documents/software/test/results/S1/alignment/final.alt.bam: 60000000 primarily aligned reads (12.7% intergenic, 62.4% touch exon, 10.9% touch intron, 14% touch both gene and not annotated regions), 0 non-mapped reads, 1763442 CBs read
/Users/lhuang/Documents/software/test/results/S1/alignment/final.alt.bam: 70000000 primarily aligned reads (12.7% intergenic, 63.1% touch exon, 10.5% touch intron, 13.7% touch both gene and not annotated regions), 0 non-mapped reads, 1955531 CBs read
/Users/lhuang/Documents/software/test/results/S1/alignment/final.alt.bam: 80000000 primarily aligned reads (12.1% intergenic, 63.8% touch exon, 10.5% touch intron, 13.7% touch both gene and not annotated regions), 0 non-mapped reads, 2155246 CBs read
/Users/lhuang/Documents/software/test/results/S1/alignment/final.alt.bam: 86716464 primarily aligned reads (11.7% intergenic, 64.6% touch exon, 9.96% touch intron, 13.7% touch both gene and not annotated regions), 0 non-mapped reads, 2284385 CBs read
Bams parsed: 00:10:07.

67065 CBs with more than 20 genes
top CBs:
4491    ATTTTGTTTTGT
4183    TGCTCTCAACGC
3629    CGGTCGAAGTGA
3395    AATAATATGGCT
3384    TCTAATCACGTC
3365    GCCCGTGGAACT
3202    CGACCCAGCAGG
3132    GTGACATCATCG
3067    GTATGGTTTACC

Start merge: 00:10:11.

**Comment by VPetukhov** [comment]
Hi,
It's shouldn't be that long. Here is the log from older version of the pipeline, when I ran it on dataset from Macosko paper:
```
/home/viktor_petukhov/dropEst2/build/dropest -M -o thousand.rds -G 500 -f -c /home/viktor_petukhov/dropEst/configs/drop_seq.xml ../GSM1544798_SpeciesMix_ThousandSTAMPs.bam 
Run: 01/16/2018 08:16:11.
Poisson Simple merge selected.

Start parse bams: 08:16:11.
../GSM1544798_SpeciesMix_ThousandSTAMPs.bam: 10000000 total reads; 36.4% intergenic; 63.6% touch exon; 0% touch intron; 0% touch not annotated regions; 356021 CBs read
../GSM1544798_SpeciesMix_ThousandSTAMPs.bam: 20000000 total reads; 37.1% intergenic; 62.9% touch exon; 0% touch intron; 0% touch not annotated regions; 594247 CBs read
../GSM1544798_SpeciesMix_ThousandSTAMPs.bam: 30000000 total reads; 38.8% intergenic; 61.2% touch exon; 0% touch intron; 0% touch not annotated regions; 811707 CBs read
../GSM1544798_SpeciesMix_ThousandSTAMPs.bam: 40000000 total reads; 38.1% intergenic; 61.9% touch exon; 0% touch intron; 0% touch not annotated regions; 982624 CBs read
../GSM1544798_SpeciesMix_ThousandSTAMPs.bam: 50000000 total reads; 38.7% intergenic; 61.3% touch exon; 0% touch intron; 0% touch not annotated regions; 1146841 CBs read
../GSM1544798_SpeciesMix_ThousandSTAMPs.bam: 60000000 total reads; 38.4% intergenic; 61.6% touch exon; 0% touch intron; 0% touch not annotated regions; 1294754 CBs read
../GSM1544798_SpeciesMix_ThousandSTAMPs.bam: 70000000 total reads; 38.4% intergenic; 61.6% touch exon; 0% touch intron; 0% touch not annotated regions; 1436656 CBs read
../GSM1544798_SpeciesMix_ThousandSTAMPs.bam: 80000000 total reads; 38.2% intergenic; 61.8% touch exon; 0% touch intron; 0% touch not annotated regions; 1560148 CBs read
../GSM1544798_SpeciesMix_ThousandSTAMPs.bam: 90000000 total reads; 37.5% intergenic; 62.5% touch exon; 0% touch intron; 0% touch not annotated regions; 1680022 CBs read
../GSM1544798_SpeciesMix_ThousandSTAMPs.bam: 100000000 total reads; 37.5% intergenic; 62.5% touch exon; 0% touch intron; 0% touch not annotated regions; 1806243 CBs read
../GSM1544798_SpeciesMix_ThousandSTAMPs.bam: 110000000 total reads; 35.9% intergenic; 64.1% touch exon; 0% touch intron; 0% touch not annotated regions; 1943556 CBs read
../GSM1544798_SpeciesMix_ThousandSTAMPs.bam: 120000000 total reads; 36% intergenic; 64% touch exon; 0% touch intron; 0% touch not annotated regions; 2070336 CBs read
../GSM1544798_SpeciesMix_ThousandSTAMPs.bam: 130000000 total reads; 35.9% intergenic; 64.1% touch exon; 0% touch intron; 0% touch not annotated regions; 2178970 CBs read
../GSM1544798_SpeciesMix_ThousandSTAMPs.bam: 140000000 total reads; 36.4% intergenic; 63.6% touch exon; 0% touch intron; 0% touch not annotated regions; 2275877 CBs read
../GSM1544798_SpeciesMix_ThousandSTAMPs.bam: 150000000 total reads; 36.7% intergenic; 63.3% touch exon; 0% touch intron; 0% touch not annotated regions; 2365867 CBs read
../GSM1544798_SpeciesMix_ThousandSTAMPs.bam: 160000000 total reads; 37% intergenic; 63% touch exon; 0% touch intron; 0% touch not annotated regions; 2452333 CBs read
ERROR: can't find chromosome, id: -1
../GSM1544798_SpeciesMix_ThousandSTAMPs.bam: 164963547 total reads; 36.8% intergenic; 63.2% touch exon; 0% touch intron; 0% touch not annotated regions; 2505864 CBs read
Bams parsed: 08:29:31.

62555 CBs with more than 20 genes
top CBs:
16034   GTTTTGAGCGAT
13437   CGCGTCTCTTCT
12538   GGCACCGTTAAT
12235   CGAGGAACTACA
12218   CGTCTCTATACA
11830   TTATCCAGCCTC
11823   CGTTCTCTCCCC
10781   CCATGTATCTCT
10418   GAAACTAATTAA

Start merge: 08:29:38.
Merge initialized: 08:31:07.
Total 10000 tags processed
Total 20000 tags processed
Total 30000 tags processed
Total 40000 tags processed
Total 50000 tags processed
Total 60000 tags processed
Total 19821 cells merged
Total 0 cells excluded
Merge finished: 08:42:59.
UMI merge start: 08:42:59.
42734 cells processed. Merged 0 UMIs from 0 cells.
UMI merge finished: 08:43:09.
42734 cells are considered as real.

4345 CBs with more than 500 genes, which have UMIs of the requested type.
top CBs:
16183   GTTTTGAGCGAT
13854   CGTCTCAATGGG
13540   CGCGTCTCTTCT
12759   GGCACCGTTAAT
12363   CGTCTCTATACA
12359   CGAGGAACTACA
11951   CGTTCTCTCCCC
11943   TTATCCAGCCTC
10879   CCATGTATCTCT

Done: 08:43:15.

41145 genes
top genes:
HUMAN_MT:1671-3229:MT-RNR2      777257
MOUSE_MT:1094-2675:mt-Rnr2      239044
HUMAN_11:10529434-10530723:MTRNR2L8     124701
HUMAN_9:19375713-19380252:RPS6  120064
HUMAN_6:26104104-26104518:HIST1H4C      92943
HUMAN_16:2012053-2014861:RPS2   87909
HUMAN_15:69745123-69748255:RPLP1        83293
HUMAN_X:118920467-118925606:RPL39       83180
MOUSE_14:105681828-105682211:Gm10076    78952
HUMAN_X:71475529-71497150:RPS4X 76619

Compiling diagnostic stats: 
Reads per chromosome per cell;
Fill exon results
Fill intron results
Fill intergenic results
Saturation info;
Mean reads per UMI;
Reads per UMI per gene;
Merge targets;
Completed.

Compiling raw count matrix: 08:45:11.
43765 genes, 42734 cells.
Done: 08:45:18.
Compiling filtered count matrix: 08:45:18.
41145 genes, 4345 cells.
Done: 08:45:28.

Writing R data to thousand.rds ...: 08:45:28.
Completed: 08:47:56.

All done: 08:48:29.
```
So, it took 30 minutes in total, and 10 minutes for merge. Are you sure that the pipeline doesn't use all your RAM and doesn't start using swap? It would slow down the work drastically.

**Comment by lxhuang7** [comment]
Hi Viktor,

Thank you for the help! I re-run the program and monitor the cpu and memory usage using 'top' command. It looks like even with a browser and a R session open, the computer still has ~14G unused physical MEM.  But half an hour in, the program is still in merging stage as I saw in the previous run.

Thanks,
Lei

$top
Processes: 362 total, 4 running, 358 sleeping, 1705 threads                                                                     17:43:25
Load Avg: 2.31, 2.21, 2.04  CPU usage: 10.46% user, 1.35% sys, 88.17% idle  SharedLibs: 231M resident, 60M data, 34M linkedit.
MemRegions: 82493 total, 10G resident, 147M private, 2192M shared. PhysMem: 18G used (3237M wired), 14G unused.
VM: 1974G vsize, 1296M framework vsize, 34397310(0) swapins, 44604245(0) swapouts.
Networks: packets: 3956525/2800M in, 2985662/1232M out. Disks: 4479227/601G read, 3304617/410G written.

PID    COMMAND      %CPU  TIME     #TH    #WQ  #PORT MEM    PURG   CMPRS  PGRP  PPID  STATE    BOOSTS           %CPU_ME %CPU_OTHRS UID
65886  top          3.7   00:00.57 1/1    0    25    3904K+ 0B     0B     65886 65272 running  *0[1]            0.00000 0.00000    0
65883  syncdefaults 0.0   00:00.12 2      1    86    8408K  0B     0B     65883 1     sleeping *1[1]            0.00000 0.00000    502
65877  jamf         0.0   00:00.03 2      1    27    2104K  0B     0B     65877 1     sleeping *0[1]            0.00000 0.00000    0
65858  com.apple.We 0.0   00:00.22 4      1    112   12M    512K   0B     65858 1     sleeping *0[34]           0.00000 0.00000    502
65857  com.apple.We 0.0   00:00.37 4      1    118   24M    2352K  0B     65857 1     sleeping *0[38]           0.00000 0.00000    502
65743  plugin-conta 0.0   00:00.70 25     1    138   24M    0B     0B     65620 65620 sleeping *0[23]           0.00000 0.00000    502
65634  plugin-conta 0.5   00:23.99 39     1    203   251M-  1224K  0B     65620 65620 sleeping *0[27]           0.00000 0.00000    502
65626  mdworker_sha 0.0   00:00.04 3      1    56    3328K  0B     0B     65626 1     sleeping *0[1]            0.00000 0.00000    502
65625  plugin-conta 0.0   00:02.29 37     1    194   167M   0B     0B     65620 65620 sleeping *0[29]           0.00000 0.00000    502
65624  plugin-conta 0.0   00:03.81 34     1    198   180M   0B     0B     65620 65620 sleeping *0[29]           0.00000 0.00000    502
65622  plugin-conta 0.0   00:11.95 40     1    250   517M   0B     0B     65620 65620 sleeping *0[29]           0.00000 0.00000    502
65620  firefox      0.2   00:50.98 64     4    743   476M-  10M    0B     65620 1     sleeping *0[223]          0.00000 0.00000    502
65476  mdworker_sha 0.0   00:00.06 3      1    50    14M    0B     0B     65476 1     sleeping *0[1]            0.00000 0.00000    89
65441  dropest      99.3  27:22.55 1/1    0    21    4842M+ 0B     0B     65413 65413 running  *0[1]            0.00000 0.00000    502

**Comment by VPetukhov** [comment]
Hm, I see...
I reran the latest version on the same data, and it also works fine. Can you try to increase "min_genes_before_merge" in the config? Just for test, I'd set it to 100, and if it works well, try to reduce it to 50. And to be on the safe side, please use "-m", but not "-M".
Alternatively, if you can share your data (my e-mail is viktor.s.petuhov@ya.ru), I can test it on our server and check if the problem is in the pipeline.

**Comment by lxhuang7** [comment]
Thanks again Viktor! I tried again but the result still the same. I have sent a link for my test data to your email address listed above. 
Best,
Lei

**Comment by lxhuang7** [comment]
I will try to run it on another machine and report back.

**Comment by lxhuang7** [comment]
I ran the program on our linux HPC with memory setting as 8Gb. It worked without any problem. 

dropest -M -f -G 100 -o $OUTDIR/dropest_count -l $OUTDIR/$sample.dropest -c $CONFIG $BAMFILE

Resource List:     nodes=1:ppn=1,walltime=24:00:00,mem=8gb,neednodes=1:ppn=1
Resources Used:    cput=00:15:36,vmem=10962436kb,walltime=00:27:32,mem=8388512kb,energy_used=0

I  am not sure whether the issue I ran into at merge step on Mac OS has something to do with the operating system or not.
