### ISSUE TITLE
Running DropTag/est for SeqWell

### ISSUE THREAD

**Issue by tiagobrc** [hms-dbmi/dropEst#59]
Hi, I have a set of data sequenced using SeqWell.
Basically, 

I have an R1 read with 20 nt in length, of which 12 are is the cell barcode and 8 are the UMI.
and an R2 gene read.

Is it possible to adapt the config file for this configuration?

Thanks!

**Comment by VPetukhov** [comment]
Hi,
It looks similar to [SPLiT-seq](https://github.com/hms-dbmi/dropEst#split-seq), which I just added in 0.8.5 version. So you can try to change its [config file](https://github.com/hms-dbmi/dropEst/blob/master/configs/split_seq.xml):
```
<barcode_starts>0</barcode_starts>
<barcode_lengths>12</barcode_lengths>
<umi_start>12</umi_start>
<umi_length>8</umi_length>
```

Could you please tell me if it works or not, so I either try to find better solution or add SeqWell to the documentation?

**Comment by tiagobrc** [comment]
Hi,

Thanks so much for your help!! It looks like it is running super nicely now.
I Update the comment when it is finished!


Thanks again!

**Comment by VPetukhov** [comment]
Thank you for the information!

**Comment by tiagobrc** [comment]
So after testing, dropTag seems to be working quite smoothly. Just a question, I did not understand exactly what is the -r [pipeline_res.params.gz]. Could you please try to explain it to me?


Thanks!!

**Comment by VPetukhov** [comment]
If you use [`-s` option of droptag](https://github.com/hms-dbmi/dropEst#droptag), the pipelines saves all metainformation about reads to a separate `.params.gz` file. It's the only way to forward barcode quality to dropest phase. If you used `droptag -s`, you need to pass this file to `dropest` wits `-r` option. Without `-s`, you won't be able to use Bayesian UMI correction. Though, in many cases you don't need it, so you can just avoid `-r` and `-s`.

**Comment by tiagobrc** [comment]
> > So after testing, dropTag seems to be working quite smoothly.
> 
> Thanks for the update!
> 
> If you use [`-s` option of droptag](https://github.com/hms-dbmi/dropEst#droptag), the pipelines saves all metainformation about reads to a separate `.params.gz` file. It's the only way to forward barcode quality to dropest phase. If you used `droptag -s`, you need to pass this file to `dropest` wits `-r` option. Without `-s`, you won't be able to use Bayesian UMI correction. Though, in many cases you don't need it, so you can just avoid `-r` and `-s`.

Fantastic explanation! Thank you!!
