### ISSUE TITLE
Question regarding the -V option output

### ISSUE THREAD

**Issue by chlee-tabin** [hms-dbmi/dropEst#61]
Hi,

I am trying to use the output from the dropEst to the velocyto(.R). I notice that most of the documentation are referring to "spliced", "unspliced", "ambiguous" counts, whereas the output matrix from dropEst after `-V` option contains "exon", "intron", "spanning". Do these latter three corresponds to the former three? Or shall I follow the velocyto CLI tutorial to create loom files?

**Comment by Zifeng1995** [comment]
> 你好
> 
> 我正在尝试使用dropEst到velocyto（.R）的输出。我注意到大多数文档都引用“拼接”，“未拼接”，“模棱两可”的计数，而`-V`选项之后dropEst的输出矩阵包含“ exon”，“ intron”，“ spanning”。后三个与前三个相对应吗？还是我应该按照velocyto CLI教程来创建织机文件？

Excuse me，have you solve this problem now?

**Comment by pkharchenko** [comment]
The three classes don’t correspond to the ones used by the py version exactly.
Intron matrix counts all the molecules that were seen fully within introns; spanning molecules span both an exon and an intron. 
Hence intron+spanning would represent all unspliced molecules, and are used as the second matrix (in addition to exon) in velocity calculations.

**Comment by Zifeng1995** [comment]
> The three classes don’t correspond to the ones used by the py version exactly. Intron matrix counts all the molecules that were seen fully within introns; spanning molecules span both an exon and an intron. Hence intron+spanning would represent all unspliced molecules, and are used as the second matrix (in addition to exon) in velocity calculations.
> […](#)
> On Jul 9, 2020, at 03:49, Ann Li ***@***.***> wrote: 你好 我正在尝试使用dropEst到velocyto（.R）的输出。我注意到大多数文档都引用“拼接”，“未拼接”，“模棱两可”的计数，而-V选项之后dropEst的输出矩阵包含“ exon”，“ intron”，“ spanning”。后三个与前三个相对应吗？还是我应该按照velocyto CLI教程来创建织机文件？ Excuse me，have you solve this problem now? — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

so I need to merge the intron matrix with the spanning matrix and sum the reads?

**Comment by pkharchenko** [comment]
> so I need to merge the intron matrix with the spanning matrix and sum the reads?

Yes. Though in practice there are very few spanning reads, so adding them makes little difference. They were originally used as a validation/test against non-coding RNAs.

**Comment by jinyoung5484** [comment]
Hello @pkharchenko,

I am using dropEst for scVelo input, but I was wondering about this issue too. So should I add the spanning reads to both intronic and exonic matrices? Also, if you have used scVelo with dropEst output, can you briefly explain how you did this process? Or the process of getting loom file from dropEst output.
