### ISSUE TITLE
Error in UMI correction vignette

### ISSUE THREAD

**Issue by connersk** [hms-dbmi/dropEst#66]
Hi,

I believe that there is an error in the UMI correction vignette similar to the error cell quality vignette in #65. I commented there but just wanted to post as a separate issue so that it didn't get lost.

When I run the GetUmisDistribution function, I get the error:

Error in GetUmisDistributionOld(reads.per.umi.per.cb, smooth = smooth) :
could not find function "GetUmisDistributionOld"

Which I believe indicates that the GetUMIsDistributionOld function isn't is not exported from the DropestR namespace.

**Comment by VPetukhov** [comment]
Hi,

I decided to drop support of data, produced by versions earlier than 0.7.5. But now the vignette should work. Please, check the latest version of the package.

**Comment by evanbiederstedt** [comment]
I think this is indeed fixed: https://github.com/kharchenkolab/dropestr/blob/master/vignettes/umi-correction.Rmd
