### ISSUE TITLE
Error during Scanning dependencies of target TestEstimation

### ISSUE THREAD

**Issue by nbartonicek** [hms-dbmi/dropEst#7]
I used cmake/2.8.10.2 (cmake3 had a bug), boost 1.6.0 during compilation.
However, compiling fails at 90% (TestEstimation step) with the error below. Any ideas what might be going on?

> CMakeFiles/TestEstimation.dir/Tests/TestEstimation.cpp.o:
> 
>  In function `_ZN5boost10test_tools9tt_detail10check_frwdINS1_15equal_impl_frwdEliEEbT_RKNS_9unit_test12lazy_ostreamENS5_13basic_cstringIKcEEmNS1_10tool_levelENS1_10check_typeERKT0_PSA_RKT1_SH_.constprop.507':
> TestEstimation.cpp:(.text+0x448): undefined reference to `boost::test_tools::tt_detail::report_assertion(boost::test_tools::assertion_result const&, boost::unit_test::lazy_ostream const&, boost::unit_test::basic_cstring<char const>, unsigned long, boost::test_tools::tt_detail::tool_level, boost::test_tools::tt_detail::check_type, unsigned long, ...)'
> ...
> collect2: error: ld returned 1 exit status
> make[2]: *** [TestEstimation] Error 1
> make[1]: *** [CMakeFiles/TestEstimation.dir/all] Error 2
> make: *** [all] Error 2

**Comment by ahy1221** [comment]
I also failed on almost the same error using boost 1.65.1.
The solution is to use a lower version libboost.
I finally work it out by using boost 1.58.0 either in a remote cluster or my local ubuntu 14.04 .
Hope this help

**Comment by Puriney** [comment]
Same failure.

cmake version 2.8.12.2
gcc (GCC) 5.2.0
boost/1.55.0
bamtools/2.3.0

**Comment by VPetukhov** [comment]
Can you please specify your linux distribution?

**Comment by Puriney** [comment]
I am about to install all dependencies from `conda`, and report if the installation works.
```
conda install -c anaconda cmake
conda install -c anaconda gcc
conda install -c anaconda zlib
conda install -c anaconda boost
conda install -c bioconda bamtools
conda install -c r r
```

**Comment by VPetukhov** [comment]
Thank you for the information. Will be waiting for your results. Anyway, tomorrow I'll try to reproduce it in docker.

**Comment by abhaduri** [comment]
I had the same issue at the same step! I tried it with both boost 1.61.0 and 1.58.0 based upon the above advice and it still failed. Any help would be appreciated, got so close! 

[ 90%] Building CXX object CMakeFiles/TestEstimation.dir/Tests/TestEstimation.cpp.o
Linking CXX executable TestEstimation
libDropTools.a(Logs.cpp.o): In function `boost::log::v2_mt_posix::sinks::synchronous_sink<boost::log::v2_mt_posix::sinks::basic_text_ostream_backend<char> >::consume(boost::log::v2_mt_posix::record_view const&)':
Logs.cpp:(.text._ZN5boost3log11v2_mt_posix5sinks16synchronous_sinkINS2_26basic_text_ostream_backendIcEEE7consumeERKNS1_11record_viewE[_ZN5boost3log11v2_mt_posix5sinks16synchronous_sinkINS2_26basic_text_ostream_backendIcEEE7consumeERKNS1_11record_viewE]+0x2c4): undefined reference to `boost::log::v2_mt_posix::sinks::basic_text_ostream_backend<char>::consume(boost::log::v2_mt_posix::record_view const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
libDropTools.a(Logs.cpp.o): In function `boost::log::v2_mt_posix::sinks::synchronous_sink<boost::log::v2_mt_posix::sinks::text_file_backend>::consume(boost::log::v2_mt_posix::record_view const&)':
Logs.cpp:(.text._ZN5boost3log11v2_mt_posix5sinks16synchronous_sinkINS2_17text_file_backendEE7consumeERKNS1_11record_viewE[_ZN5boost3log11v2_mt_posix5sinks16synchronous_sinkINS2_17text_file_backendEE7consumeERKNS1_11record_viewE]+0x2c4): undefined reference to `boost::log::v2_mt_posix::sinks::text_file_backend::consume(boost::log::v2_mt_posix::record_view const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
libDropTools.a(Logs.cpp.o): In function `void boost::log::v2_mt_posix::basic_formatting_ostream<char, std::char_traits<char>, std::allocator<char> >::aligned_write<wchar_t>(wchar_t const*, long)':
Logs.cpp:(.text._ZN5boost3log11v2_mt_posix24basic_formatting_ostreamIcSt11char_traitsIcESaIcEE13aligned_writeIwEEvPKT_l[_ZN5boost3log11v2_mt_posix24basic_formatting_ostreamIcSt11char_traitsIcESaIcEE13aligned_writeIwEEvPKT_l]+0x75): undefined reference to `boost::log::v2_mt_posix::aux::code_convert(wchar_t const*, unsigned long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::locale const&)'
Logs.cpp:(.text._ZN5boost3log11v2_mt_posix24basic_formatting_ostreamIcSt11char_traitsIcESaIcEE13aligned_writeIwEEvPKT_l[_ZN5boost3log11v2_mt_posix24basic_formatting_ostreamIcSt11char_traitsIcESaIcEE13aligned_writeIwEEvPKT_l]+0x117): undefined reference to `boost::log::v2_mt_posix::aux::code_convert(wchar_t const*, unsigned long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::locale const&)'
libDropTools.a(Logs.cpp.o): In function `void boost::log::v2_mt_posix::type_dispatcher::callback_base::trampoline<boost::log::v2_mt_posix::binder1st<boost::log::v2_mt_posix::output_fun, boost::log::v2_mt_posix::expressions::aux::stream_ref<boost::log::v2_mt_posix::basic_formatting_ostream<char, std::char_traits<char>, std::allocator<char> > >&>, std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > >(void*, std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > const&)':
Logs.cpp:(.text._ZN5boost3log11v2_mt_posix15type_dispatcher13callback_base10trampolineINS1_9binder1stINS1_10output_funERNS1_11expressions3aux10stream_refINS1_24basic_formatting_ostreamIcSt11char_traitsIcESaIcEEEEEEENSt7__cxx1112basic_stringIwSB_IwESaIwEEEEEvPvRKT0_[_ZN5boost3log11v2_mt_posix15type_dispatcher13callback_base10trampolineINS1_9binder1stINS1_10output_funERNS1_11expressions3aux10stream_refINS1_24basic_formatting_ostreamIcSt11char_traitsIcESaIcEEEEEEENSt7__cxx1112basic_stringIwSB_IwESaIwEEEEEvPvRKT0_]+0x62): undefined reference to `boost::log::v2_mt_posix::aux::code_convert(wchar_t const*, unsigned long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::locale const&)'
libDropTools.a(Logs.cpp.o): In function `boost::log::v2_mt_posix::sinks::synchronous_sink<boost::log::v2_mt_posix::sinks::text_file_backend>::try_consume(boost::log::v2_mt_posix::record_view const&)':
Logs.cpp:(.text._ZN5boost3log11v2_mt_posix5sinks16synchronous_sinkINS2_17text_file_backendEE11try_consumeERKNS1_11record_viewE[_ZN5boost3log11v2_mt_posix5sinks16synchronous_sinkINS2_17text_file_backendEE11try_consumeERKNS1_11record_viewE]+0x2f3): undefined reference to `boost::log::v2_mt_posix::sinks::text_file_backend::consume(boost::log::v2_mt_posix::record_view const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
libDropTools.a(Logs.cpp.o): In function `boost::log::v2_mt_posix::sinks::synchronous_sink<boost::log::v2_mt_posix::sinks::basic_text_ostream_backend<char> >::try_consume(boost::log::v2_mt_posix::record_view const&)':
Logs.cpp:(.text._ZN5boost3log11v2_mt_posix5sinks16synchronous_sinkINS2_26basic_text_ostream_backendIcEEE11try_consumeERKNS1_11record_viewE[_ZN5boost3log11v2_mt_posix5sinks16synchronous_sinkINS2_26basic_text_ostream_backendIcEEE11try_consumeERKNS1_11record_viewE]+0x2f3): undefined reference to `boost::log::v2_mt_posix::sinks::basic_text_ostream_backend<char>::consume(boost::log::v2_mt_posix::record_view const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
CMakeFiles/TestEstimation.dir/Tests/TestEstimation.cpp.o: In function `boost::unit_test::make_test_case(boost::unit_test::callback0<boost::unit_test::ut_detail::unused> const&, boost::unit_test::basic_cstring<char const>)':
TestEstimation.cpp:(.text._ZN5boost9unit_test14make_test_caseERKNS0_9callback0INS0_9ut_detail6unusedEEENS0_13basic_cstringIKcEE[_ZN5boost9unit_test14make_test_caseERKNS0_9callback0INS0_9ut_detail6unusedEEENS0_13basic_cstringIKcEE]+0x16): undefined reference to `_ZN5boost9unit_test9ut_detail24normalize_test_case_nameB5cxx11ENS0_13basic_cstringIKcEE'
collect2: error: ld returned 1 exit status
make[2]: *** [TestEstimation] Error 1
make[1]: *** [CMakeFiles/TestEstimation.dir/all] Error 2
make: *** [all] Error 2

**Comment by VPetukhov** [comment]
> cmake version 2.8.12.2
> gcc (GCC) 5.2.0
> boost/1.55.0
> bamtools/2.3.0

I failed to reproduce this issue on the same software (see [Dockerfile](https://github.com/hms-dbmi/dropEst/blob/master/dockers/centos6/Dockerfile)). Please, check if the docker instructions work for you.

**Comment by VPetukhov** [comment]
Will reopen if someone reproduce the error
