### ISSUE TITLE
Loading 10X data for dropestr?

### ISSUE THREAD

**Issue by sanofi-pi** [hms-dbmi/dropEst#71]
Hi,

How do you load 10X data for dropestr? The vignettes start by loading a pre-compiled .rds file (for example, this vignette: https://vpetukhov.github.io/dropEstAnalysis/umi_correction__umi_bmmc1.html). Ideally, dropestr should have a wrapper function that loads 10X data directly into the "reads_per_umi_per_cell" list structure, enabling ease of use. Does this functionality exist in R, python or bash? 

Best regards,

Mat

**Comment by VPetukhov** [comment]
Hi,
You already have it in the rds, unless you use [`-u` option](https://github.com/hms-dbmi/dropEst#command-line-arguments-for-dropest):
```R
holder <- readRDS('./cell.counts.rds')
str(holder$reads_per_umi_per_cell)
```
