### ISSUE TITLE
dropest for Drop-Seq aligned, tagged bam

### ISSUE THREAD

**Issue by joshua-gould** [hms-dbmi/dropEst#75]
I'm trying to run dropest with an aligned, tagged bam from the Drop-Seq pipeline from the McCarrol lab and am getting the error "Wrong quality length: 16, expected: 0"-do you know what the issue could be? Thanks.

**Comment by VPetukhov** [comment]
Please, check https://github.com/hms-dbmi/dropEst/issues/35
