### ISSUE TITLE
cmake error to find the boost library

### ISSUE THREAD

**Issue by liuyongdk** [hms-dbmi/dropEst#76]
Hi, Viktor, 
I have an issue with running cmake. I am using centos 7.
Here is the log,

**(base) [ly@localhost boost_1_69_0]$ ./bootstrap.sh --with-libraries=filesystem,iostreams,log,system,thread,test**
Building Boost.Build engine with toolset gcc... tools/build/src/engine/bin.linuxx86_64/b2
Unicode/ICU support for Boost.Regex?... /usr
Backing up existing Boost.Build configuration in project-config.jam.4
Generating Boost.Build configuration in project-config.jam...

Bootstrapping is done. To build, run:

    ./b2
    
To adjust configuration, edit 'project-config.jam'.
Further information:

   - Command line help:
     ./b2 --help
     
   - Getting started guide: 
     http://www.boost.org/more/getting_started/unix-variants.html
     
   - Boost.Build documentation:
     http://www.boost.org/build/doc/html/index.html

**(base) [ly@localhost boost_1_69_0]$ ./b2 cxxflags="-std=c++11" include="$LOCAL_LIBS/include/" search="$LOCAL_LIBS/lib/" link=shared threading=multi install --prefix=$LOCAL_LIBS**
Performing configuration checks

    - default address-model    : 64-bit (cached)
    - default architecture     : x86 (cached)
    - zlib                     : yes (cached)
    - bzip2                    : yes (cached)
    - lzma                     : yes (cached)
    - zstd                     : no  (cached)
    - native-atomic-int32-supported : yes (cached)
    - native-syslog-supported  : yes (cached)
    - pthread-supports-robust-mutexes : yes (cached)
    - compiler-supports-ssse3  : yes (cached)
    - compiler-supports-avx2   : yes (cached)
    - has_icu builds           : yes (cached)
    - lockfree boost::atomic_flag : yes (cached)
    - BOOST_COMP_GNUC >= 4.3.0 : no  (cached)

Component configuration:

    - atomic                   : not building
    - chrono                   : not building
    - container                : not building
    - context                  : not building
    - contract                 : not building
    - coroutine                : not building
    - date_time                : not building
    - exception                : not building
    - fiber                    : not building
    - filesystem               : building
    - graph                    : not building
    - graph_parallel           : not building
    - iostreams                : building
    - locale                   : not building
    - log                      : building
    - math                     : not building
    - mpi                      : not building
    - program_options          : not building
    - python                   : not building
    - random                   : not building
    - regex                    : not building
    - serialization            : not building
    - stacktrace               : not building
    - system                   : building
    - test                     : building
    - thread                   : building
    - timer                    : not building
    - type_erasure             : not building
    - wave                     : not building

...patience...
...patience...
...patience...
...patience...
...found 32827 targets...
...updating 3 targets...
gcc.link.dll bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/libboost_log.so.1.69.0
/usr/bin/ld: cannot find -lboost_filesystem
/usr/bin/ld: cannot find -lboost_atomic
/usr/bin/ld: cannot find -lboost_date_time
/usr/bin/ld: cannot find -lboost_regex
/usr/bin/ld: cannot find -lboost_thread
/usr/bin/ld: cannot find -lboost_chrono
/usr/bin/ld: cannot find -lboost_system
collect2: error: ld returned 1 exit status

    "g++" -L"/home/ly/local//lib" -L"/usr/bin" -L"/usr/lib"   -o "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/libboost_log.so.1.69.0" -Wl,-h -Wl,libboost_log.so.1.69.0 -shared -Wl,--start-group "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/attribute_name.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/attribute_set.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/attribute_value_set.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/code_conversion.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/core.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/record_ostream.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/severity_level.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/global_logger_storage.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/named_scope.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/process_name.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/process_id.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/thread_id.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/timer.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/exceptions.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/default_attribute_names.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/default_sink.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/text_ostream_backend.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/text_file_backend.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/text_multifile_backend.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/thread_specific.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/once_block.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/timestamp.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/threadsafe_queue.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/event.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/trivial.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/spirit_encoding.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/format_parser.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/date_time_format_parser.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/named_scope_format_parser.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/unhandled_exception_count.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/permissions.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/dump.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/dump_avx2.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/dump_ssse3.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/posix/ipc_reliable_message_queue.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/posix/object_name.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/syslog_backend.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/codecvt_error_category.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/operations.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/path.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/path_traits.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/portability.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/unique_path.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/utf8_codecvt_facet.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/windows_file_codecvt.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/error_code.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/lockpool.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/gregorian/greg_month.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/gregorian/greg_weekday.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/gregorian/date_generators.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/c_regex_traits.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/cpp_regex_traits.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/cregex.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/fileiter.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/icu.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/instances.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/posix_api.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/regex.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/regex_debug.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/regex_raw_buffer.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/regex_traits_defaults.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/static_mutex.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/w32_regex_traits.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/wc_regex_traits.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/wide_posix_api.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/winstances.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/usinstances.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/pthread/thread.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/pthread/once.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/future.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/chrono.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/thread_clock.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/process_cpu_clocks.o"  -Wl,-Bstatic  -Wl,-Bdynamic -lrt -lboost_filesystem -lrt -lboost_atomic -lboost_date_time -lboost_regex -licuuc -licui18n -licudata -lboost_thread -lboost_chrono -lboost_system -Wl,--end-group -fPIC -m64 -pthread -fvisibility=hidden -fvisibility-inlines-hidden 

...failed gcc.link.dll bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/libboost_log.so.1.69.0...
...skipped <p/home/ly/local/lib>libboost_log.so.1.69.0 for lack of <pbin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden>libboost_log.so.1.69.0...
...skipped <p/home/ly/local/lib>libboost_log.so for lack of <p/home/ly/local/lib>libboost_log.so.1.69.0...
...failed updating 1 target...
...skipped 2 targets...

**(base) [ly@localhost build]$ cmake .. && make**
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread_kill
-- Looking for pthread_kill - not found
CMake Error at /home/ly/local/share/cmake-3.14/Modules/FindBoost.cmake:2124 (message):
  Unable to find the requested Boost libraries.

  Boost version: 1.69.0

  Boost include path: /home/ly/local/include

  Could not find the following Boost libraries:

          boost_filesystem
          boost_log
          boost_system
          boost_thread
          boost_unit_test_framework

  Some (but not all) of the required Boost libraries were found.  You may
  need to install these additional Boost libraries.  Alternatively, set
  BOOST_LIBRARYDIR to the directory containing Boost libraries or BOOST_ROOT
  to the location of Boost.
Call Stack (most recent call first):
  CMake/deps.cmake:19 (find_package)
  CMakeLists.txt:18 (include)

CMake Warning (dev) at CMake/deps.cmake:34 (find_package):
  Policy CMP0074 is not set: find_package uses <PackageName>_ROOT variables.
  Run "cmake --help-policy CMP0074" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  CMake variable R_ROOT is set to:

    /usr/lib64/R

  For compatibility, CMake is ignoring the variable.
Call Stack (most recent call first):
  CMakeLists.txt:18 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found R: /usr/lib64/R
-- Configuring incomplete, errors occurred!
See also "/home/ly/dropEst/build/CMakeFiles/CMakeOutput.log".
See also "/home/ly/dropEst/build/CMakeFiles/CMakeError.log".
(base) [ly@localhost build]$ cd /home/ly/local/include

**Comment by VPetukhov** [comment]
Hi,
It looks like you have some problems with boost compilation (from your log):

```
gcc.link.dll bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/libboost_log.so.1.69.0
/usr/bin/ld: cannot find -lboost_filesystem
/usr/bin/ld: cannot find -lboost_atomic
/usr/bin/ld: cannot find -lboost_date_time
/usr/bin/ld: cannot find -lboost_regex
/usr/bin/ld: cannot find -lboost_thread
/usr/bin/ld: cannot find -lboost_chrono
/usr/bin/ld: cannot find -lboost_system
collect2: error: ld returned 1 exit status

"g++" -L"/home/ly/local//lib" -L"/usr/bin" -L"/usr/lib"   -o "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/libboost_log.so.1.69.0" -Wl,-h -Wl,libboost_log.so.1.69.0 -shared -Wl,--start-group "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/attribute_name.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/attribute_set.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/attribute_value_set.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/code_conversion.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/core.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/record_ostream.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/severity_level.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/global_logger_storage.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/named_scope.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/process_name.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/process_id.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/thread_id.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/timer.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/exceptions.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/default_attribute_names.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/default_sink.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/text_ostream_backend.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/text_file_backend.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/text_multifile_backend.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/thread_specific.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/once_block.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/timestamp.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/threadsafe_queue.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/event.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/trivial.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/spirit_encoding.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/format_parser.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/date_time_format_parser.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/named_scope_format_parser.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/unhandled_exception_count.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/permissions.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/dump.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/dump_avx2.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/dump_ssse3.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/posix/ipc_reliable_message_queue.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/posix/object_name.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/syslog_backend.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/codecvt_error_category.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/operations.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/path.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/path_traits.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/portability.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/unique_path.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/utf8_codecvt_facet.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/windows_file_codecvt.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/error_code.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/lockpool.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/gregorian/greg_month.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/gregorian/greg_weekday.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/gregorian/date_generators.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/c_regex_traits.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/cpp_regex_traits.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/cregex.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/fileiter.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/icu.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/instances.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/posix_api.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/regex.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/regex_debug.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/regex_raw_buffer.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/regex_traits_defaults.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/static_mutex.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/w32_regex_traits.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/wc_regex_traits.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/wide_posix_api.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/winstances.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/usinstances.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/pthread/thread.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/pthread/once.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/future.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/chrono.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/thread_clock.o" "bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/process_cpu_clocks.o"  -Wl,-Bstatic  -Wl,-Bdynamic -lrt -lboost_filesystem -lrt -lboost_atomic -lboost_date_time -lboost_regex -licuuc -licui18n -licudata -lboost_thread -lboost_chrono -lboost_system -Wl,--end-group -fPIC -m64 -pthread -fvisibility=hidden -fvisibility-inlines-hidden 

...failed gcc.link.dll bin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden/libboost_log.so.1.69.0...
...skipped <p/home/ly/local/lib>libboost_log.so.1.69.0 for lack of <pbin.v2/libs/log/build/gcc-4.8.5/release/threadapi-pthread/threading-multi/visibility-hidden>libboost_log.so.1.69.0...
...skipped <p/home/ly/local/lib>libboost_log.so for lack of <p/home/ly/local/lib>libboost_log.so.1.69.0...
...failed updating 1 target...
...skipped 2 targets...
```

And as a general rule, I would avoid to use the very latest version of boost in favor of something more stable (1.60 maybe?). Especially it's important for older gcc versions, such as 4.8.5, even though it's claimed to be compatible. Not sure that it's the root of the problem though.
