### ISSUE TITLE
Automated way to update dropEst inside Docker

### ISSUE THREAD

**Issue by wikiselev** [hms-dbmi/dropEst#77]
Could the dropest docker image (https://hub.docker.com/r/vpetukhov/dropest/) be updated to include the recent changes? It would also be good to tag it with the version corresponding to the version of dropest?

**Comment by VPetukhov** [comment]
Indeed, the docker is not connected to a specific code version. It contains the latest code at the moment you built it. I added [instruction](https://github.com/hms-dbmi/dropEst#updating-dropest-inside-docker) to the readme on how to update the docker.

**Comment by wikiselev** [comment]
It would be good to automate this with e.g. Travis (https://travis-ci.org).

**Comment by wikiselev** [comment]
sorry I meant DockerHub or quay.io web hooks...

**Comment by VPetukhov** [comment]
Nice suggestion! Will try to do that.

**Comment by VPetukhov** [comment]
So, I configured automated builds and updated Docker part of the README. Now only need to wait till DockerHub will build the image (which takes some time).
