### ISSUE TITLE
Future of dropEst

### ISSUE THREAD

**Issue by wikiselev** [hms-dbmi/dropEst#78]
Hello, I have a question about dropEst support. It looks like a really cool tool and we would like to invest in integrating to our pipelines mainly because it can cover so many different protocols. However, I've noticed that there has been no response to any of my issues here for a while. So, my question is - is there a long-term plan on supporting this project? Or it has just been a PhD/Postdoc project and there is no plan on supporting it in the future? We need to make a critical decision now and would like to know what is happening with dropEst.

**Comment by VPetukhov** [comment]
Hello Vladimir,
In long term, we plan to support dropEst by adding new protocols and fixing some bugs if any, but at the moment we don't expect to have any major improvements. About the issues, sorry for the delay with it, but time I can spend on it is quite limited. And, being fair, I don't expect that it will change in the nearest future.
If you by any chance have some suggestion on how to deal with such issues without hiring half-time a person solely for dropEst support (some way to stimulate community, maybe) we'd be happy to discuss it. :)

**Comment by wikiselev** [comment]
Ok, thanks for letting me know! It would be great to stimulate community (including us), especially because there is no other tool available with the same comprehensive functionality. If we decide to go with dropEst we may be able to have one of our developers partly working on it, but your responsiveness would be essential for this to work. We have a large spectrum of different protocols to support and it would be beneficial for us to have a single tool. Would you like to have a call to discuss the long-term support?

**Comment by VPetukhov** [comment]
Sure, thanks! Please, drop me a message at viktor.s.petuhov@ya.ru and let's arrange the time.

**Comment by pkharchenko** [comment]
Yes, happy to discuss. We’d be glad to engage developers who’d be interested in maintaining or improving dropEst.
Best,
-peter.
