### ISSUE TITLE
Location of built images

### ISSUE THREAD

**Issue by sgosline** [hms-dbmi/dropEst#79]
Are the docker images built on a place such as Quai.io or dockerhub where I can pull them directly?

**Comment by VPetukhov** [comment]
We're going to set up a way to build containers and push them to the cloud (see https://github.com/hms-dbmi/dropEst/issues/77), but at the moment there are no pre-built images.

**Comment by sgosline** [comment]
Awesome, I put one [here](https://hub.docker.com/r/sgosline/dropest) for now, as I begin to test out how to build your tool into some of our workflows.

**Comment by VPetukhov** [comment]
Thank you so much!

**Comment by sgosline** [comment]
Great!
