### ISSUE TITLE
How can I get 10x.xml config file for Dropest?

### ISSUE THREAD

**Issue by Sophia409** [hms-dbmi/dropEst#81]
Hello,
I'm trying DropEst in the 10X scRNAseq data (https://support.10xgenomics.com/single-cell-gene-expression/datasets/2.1.0/neurons_900) for velocyto. 
I began with FASTQ files that have already been demultiplexed with bcl2fastq directly and I use cellranger3 to get the outs folder and bam file. But I don't know how to get 10x.xml config file that DropEst pipeline mentions. 
`dropest [options] -f [-g ./genes.gtf] -c ./config.xml ./pipeline_res_*.bam`
Where can I  find and download it？Is it a general file or personal file?I found there is a config.xml in a[ online tutorial](https://davetang.org/muse/2018/08/09/getting-started-with-cell-ranger/),but I'm not sure about it.Can you give me some help?
![图片](https://user-images.githubusercontent.com/30619010/55234870-0aee2880-5267-11e9-9148-cdcfa7da13ea.png)

**Comment by VPetukhov** [comment]
Hi,

For 10x you don't need droptag (see [manual](https://github.com/hms-dbmi/dropEst#usage-of-tagged-bam-files-eg-10x-drop-seq-as-input)). Config file is exactly in the dropEst project folder *dropEst/configs/10x.xml* (see it also [here](https://github.com/hms-dbmi/dropEst/blob/master/configs/10x.xml)).

**Comment by Sophia409** [comment]
@VPetukhov Thank you a lot.So if I install R packages following Dropest tutorial,the 10x.xml file would exist in the folder automatically.I don't know if I got it right?

**Comment by VPetukhov** [comment]
@Sophia409, it's not in the package folder, it's in the folder of the pipeline. See [installation](https://github.com/hms-dbmi/dropEst#installation) section, part `git clone https://github.com/hms-dbmi/dropEst.git`
