### ISSUE TITLE
Readme DropSeq Protocol Missing

### ISSUE THREAD

**Issue by davisidarta** [hms-dbmi/dropEst#82]
Hello, dropEst team!

First of all, thank you for making this super cool and comprehensive scRNAseq analysis tool avaiable!

I`ve already performed many scRNAseq analysis, but always starting from an expression matrix. I`m now learning how to use dropEst to produce bam files to give as an input to velocyto.R.

The thing is there is no DropSeq protocol at the ReadMe file. How should I edit the config file in order to start my analysis?

Thank you very much in advance for the help! Any insights are very welcome!

Best regards,

Davi

**Comment by VPetukhov** [comment]
Hello @davisidarta ,
It's not in the readme, bug we have [documentation for DropSeq](https://dropest.readthedocs.io/en/latest/droptag.html#drop-seq). Is it what you're looking for?
