### ISSUE TITLE
[help wanted] dropestr usage

### ISSUE THREAD

**Issue by cstrlln** [hms-dbmi/dropEst#83]
Hello, just starting to work with single cell RNAseq so please bear with me.
I found the vignettes for dropestr a bit complicated to follow.
For those of you who have managed to use the dropestr package, and used the filtered cells and UMI corrected cm for downstream applications could you please share a simple pipeline for guidance.
thank you!

**Comment by evanbiederstedt** [comment]
I've tried updating some of this here: https://github.com/kharchenkolab/dropestr

We will work on improving the documentation
