### ISSUE TITLE
bzip2 make -f Makefile-libbz2_so error

### ISSUE THREAD

**Issue by reginawongg** [hms-dbmi/dropEst#88]
Hi, 

I used this wget https://fossies.org/linux/misc/bzip2-1.0.6.tar.gz to download my bzip2 file because the link listed in the setup manual is broken, and the link listed in #40 isn't working. It seemed to work until I ran make -f Makefile-libbz2_so and got the following error. 

Does anyone have a solution?

(base) MacBook-Pro-3:~ regwang$ cd bzip2-1.0.6
(base) MacBook-Pro-3:bzip2-1.0.6 regwang$ make -f Makefile-libbz2_so
gcc -fpic -fPIC -Wall -Winline -O2 -g -D_FILE_OFFSET_BITS=64 -c blocksort.c
In function ‘mainSort’:
blocksort.c:347:6: warning: inlining failed in call to ‘mainGtU.part.0’: call is unlikely and code size would grow [-Winline]
 Bool mainGtU ( UInt32  i1, 
      ^
cc1: warning: called from here [-Winline]
blocksort.c:347:6: warning: inlining failed in call to ‘mainGtU.part.0’: call is unlikely and code size would grow [-Winline]
 Bool mainGtU ( UInt32  i1, 
      ^
cc1: warning: called from here [-Winline]
blocksort.c:347:6: warning: inlining failed in call to ‘mainGtU.part.0’: call is unlikely and code size would grow [-Winline]
 Bool mainGtU ( UInt32  i1, 
      ^
cc1: warning: called from here [-Winline]
gcc -fpic -fPIC -Wall -Winline -O2 -g -D_FILE_OFFSET_BITS=64 -c huffman.c
gcc -fpic -fPIC -Wall -Winline -O2 -g -D_FILE_OFFSET_BITS=64 -c crctable.c
gcc -fpic -fPIC -Wall -Winline -O2 -g -D_FILE_OFFSET_BITS=64 -c randtable.c
gcc -fpic -fPIC -Wall -Winline -O2 -g -D_FILE_OFFSET_BITS=64 -c compress.c
gcc -fpic -fPIC -Wall -Winline -O2 -g -D_FILE_OFFSET_BITS=64 -c decompress.c
gcc -fpic -fPIC -Wall -Winline -O2 -g -D_FILE_OFFSET_BITS=64 -c bzlib.c
gcc -shared -Wl,-soname -Wl,libbz2.so.1.0 -o libbz2.so.1.0.6 blocksort.o huffman.o crctable.o randtable.o compress.o decompress.o bzlib.o
ld: unknown option: -soname
collect2: error: ld returned 1 exit status
make: *** [all] Error 1

**Comment by shaaaarpy** [comment]
Hi 
I just used the link in #40. Its working.

Thank you
