### ISSUE TITLE
Dropest for 10x v3 chemistry

### ISSUE THREAD

**Issue by dalhoomist** [hms-dbmi/dropEst#90]
Hi,

10x released v3 chemistry recently. Do I need to do something different with the dropest pipeline compared with the V2 chemistry? Is the 10x_aug_2016_split file good for the barcodes?

From what I can gather, the 10x V3 has 12bp UMI but still a 16bp cell barcode.

Thanks
Osama

**Comment by rrydbirk** [comment]
Indeed, v3 has 12bp UMI, so this needs to be changed in the config:
<umi_length>12</umi_length>

**Comment by dalhoomist** [comment]
That is what I thought. Thank you for the help.
