### ISSUE TITLE
Filtered cells are empty

### ISSUE THREAD

**Issue by yihming** [hms-dbmi/dropEst#91]
Hello,

I tried to use dropEst 0.8.5 to estimate the processed BAM files (after dropTag and alignment steps, and both were executed properly based on the stats). The command I use is 

`dropest -f -c config.xml -w alignment_result/alignment_*.bam`

I used the ``indrop3`` config.xml file provided in your repository.

However, the resulting count matrix contains 0 gene and 0 cell, with warning saying filtered cells are empty. Probably, filtration threshold is too strict or you forgot to run 'merge_and_filter'. Please refer to [est_main.log](https://github.com/hms-dbmi/dropEst/files/3498861/est_main.log) for its details.

So could you please help me by suggesting which configuration or command-line arguments I should adjust to get my result? Thank you!

Sincerely,
Yiming Yang

**Comment by VPetukhov** [comment]
Hi,
It means that your bam file miss either information about barcodes or about genes. Most probably, you just need to pass gtf file to dropest using `-g` option. Or it means that you used `-s` option in droptag.

**Comment by yihming** [comment]
Hi Viktor,

Thank you very much for your quick response!

I followed your suggestion to pass the gtf file using ``-g`` option in ``dropest``:

`dropest -f -c config.xml -g gene.gtf -w alignment_result/alignment_*.bam`

where ``gene.gtf`` is the hg19 reference that I generated following this [10x documentation](https://support.10xgenomics.com/single-cell-gene-expression/software/release-notes/build#hg19_3.0.0), and used in STAR alignment phase.

However, I still get the same issue as before.

For your second suspicion, I checked my ``droptag`` log, i.e. [tag_main.log](https://github.com/hms-dbmi/dropEst/files/3503574/tag_main.log), and confirmed that I didn't use ``-s`` option. 

Do you have any suggestion regarding my issue? I can provide more information if you need for your diagnosis.

Thank you!


Sincerely,
Yiming

**Comment by VPetukhov** [comment]
Hi Yiming,
Can you please share your config and several lines of one of your .bam files? The command is `samtools view ./alignment.bam| head -n 10`

**Comment by yihming** [comment]
Sure. [Here](https://github.com/hms-dbmi/dropEst/files/3503621/samtools_view_output.txt) is the screen output by running the ``samtools view`` command you sent to me.

It seems that GitHub doesn't allow me upload XML files. So I just paste it below:

<config>
    
    <TagsSearch>
        <protocol>indrop3</protocol>
        <BarcodesSearch>
            <barcode1_length>8</barcode1_length>
            <barcode2_length>8</barcode2_length>
            <umi_length>6</umi_length>
            <r1_rc_length>8</r1_rc_length>
            <max_libtag_ed> 2 </max_libtag_ed>
        </BarcodesSearch>

        <Processing>
            <min_align_length>10</min_align_length>
            <reads_per_out_file>10000000</reads_per_out_file>
        </Processing>
    </TagsSearch>

    
    <Estimation>
        <Merge>
	    <barcodes_file>/software/dropEst/data/barcodes/indrop_v3</barcodes_file>
            <barcodes_type>indrop</barcodes_type>
            <min_merge_fraction>0.2</min_merge_fraction>
            <max_cb_merge_edit_distance>2</max_cb_merge_edit_distance>
            <max_umi_merge_edit_distance>1</max_umi_merge_edit_distance>
            <min_genes_after_merge>100</min_genes_after_merge>
            <min_genes_before_merge>10</min_genes_before_merge>
        </Merge>

        <PreciseMerge>
            <max_merge_prob>1e-5</max_merge_prob>
            <max_real_merge_prob>1e-7</max_real_merge_prob>
        </PreciseMerge>
    </Estimation>
</config>

**Comment by VPetukhov** [comment]
Oh, got it. You use `-f` option, which mean that your bam file has tags with barcode and UMI sequence. It's the case if the file is produced with CellRanger. But in your case, these sequences are encoded as read names (e.g. `FTVR1!ATCGTAACTTGCACGC#TTAACG`), so you don't need to use this flag.

**Comment by yihming** [comment]
It works now by not dropping ``-f`` option when using ``dropest``. Thank you so much for your help!
