### ISSUE TITLE
CMake Error

### ISSUE THREAD

**Issue by epiBioCore** [hms-dbmi/dropEst#94]
I'm trying to compile with CMake but keep having errors with cmake not finding Boost libraries, though it has detected the correct version of Boost.
`[root@buddy build]# cmake .. -DBOOST_ROOT=/usr/local
-- [ /usr/local/share/cmake-3.15/Modules/FindBoost.cmake:1275 ] _boost_TEST_VERSIONS = "1.70.0;1.70;1.69.0;1.69;1.68.0;1.68;1.67.0;1.67;1.66.0;1.66;1.65.1;1.65.0;1.65;1.64.0;1.64;1.63.0;1.63;1.62.0;1.62;1.61.0;1.61;1.60.0;1.60;1.59.0;1.59;1.58.0;1.58;1.57.0;1.57;1.56.0;1.56;1.55.0;1.55;1.54.0;1.54"
-- [ /usr/local/share/cmake-3.15/Modules/FindBoost.cmake:1276 ] Boost_USE_MULTITHREADED = "ON"
-- [ /usr/local/share/cmake-3.15/Modules/FindBoost.cmake:1277 ] Boost_USE_STATIC_LIBS = "OFF"
-- [ /usr/local/share/cmake-3.15/Modules/FindBoost.cmake:1278 ] Boost_USE_STATIC_RUNTIME = "OFF"
-- [ /usr/local/share/cmake-3.15/Modules/FindBoost.cmake:1279 ] Boost_ADDITIONAL_VERSIONS = <unset>
-- [ /usr/local/share/cmake-3.15/Modules/FindBoost.cmake:1280 ] Boost_NO_SYSTEM_PATHS = <unset>
-- [ /usr/local/share/cmake-3.15/Modules/FindBoost.cmake:1349 ] BOOST_ROOT = "/usr/local"
-- [ /usr/local/share/cmake-3.15/Modules/FindBoost.cmake:1350 ] ENV{BOOST_ROOT} = <unset>
-- [ /usr/local/share/cmake-3.15/Modules/FindBoost.cmake:1351 ] BOOST_INCLUDEDIR = <unset>
-- [ /usr/local/share/cmake-3.15/Modules/FindBoost.cmake:1352 ] ENV{BOOST_INCLUDEDIR} = <unset>
-- [ /usr/local/share/cmake-3.15/Modules/FindBoost.cmake:1353 ] BOOST_LIBRARYDIR = <unset>
-- [ /usr/local/share/cmake-3.15/Modules/FindBoost.cmake:1354 ] ENV{BOOST_LIBRARYDIR} = <unset>
-- [ /usr/local/share/cmake-3.15/Modules/FindBoost.cmake:1442 ] location of version.hpp: /usr/local/include/boost/version.hpp
-- [ /usr/local/share/cmake-3.15/Modules/FindBoost.cmake:1482 ] Boost_VERSION = "106000"
-- [ /usr/local/share/cmake-3.15/Modules/FindBoost.cmake:1483 ] Boost_VERSION_STRING = "1.60.0"
-- [ /usr/local/share/cmake-3.15/Modules/FindBoost.cmake:1484 ] Boost_VERSION_MACRO = "106000"
-- [ /usr/local/share/cmake-3.15/Modules/FindBoost.cmake:1485 ] Boost_VERSION_MAJOR = "1"
-- [ /usr/local/share/cmake-3.15/Modules/FindBoost.cmake:1486 ] Boost_VERSION_MINOR = "60"
-- [ /usr/local/share/cmake-3.15/Modules/FindBoost.cmake:1487 ] Boost_VERSION_PATCH = "0"
-- [ /usr/local/share/cmake-3.15/Modules/FindBoost.cmake:1488 ] Boost_VERSION_COUNT = "3"
-- [ /usr/local/share/cmake-3.15/Modules/FindBoost.cmake:1505 ] Boost_LIB_PREFIX = ""
-- [ /usr/local/share/cmake-3.15/Modules/FindBoost.cmake:1506 ] Boost_NAMESPACE = "boost"
-- [ /usr/local/share/cmake-3.15/Modules/FindBoost.cmake:614 ] _boost_COMPILER = "-gcc48" (guessed)
-- [ /usr/local/share/cmake-3.15/Modules/FindBoost.cmake:1542 ] _boost_MULTITHREADED = "-mt"
-- [ /usr/local/share/cmake-3.15/Modules/FindBoost.cmake:1619 ] _boost_ARCHITECTURE_TAG = "" (detected)
-- [ /usr/local/share/cmake-3.15/Modules/FindBoost.cmake:1623 ] _boost_RELEASE_ABI_TAG = "-"
-- [ /usr/local/share/cmake-3.15/Modules/FindBoost.cmake:1624 ] _boost_DEBUG_ABI_TAG = "-d"
-- [ /usr/local/share/cmake-3.15/Modules/FindBoost.cmake:1684 ] _boost_LIBRARY_SEARCH_DIRS_RELEASE = "/usr/local/lib;NO_DEFAULT_PATH;NO_CMAKE_FIND_ROOT_PATH"
-- [ /usr/local/share/cmake-3.15/Modules/FindBoost.cmake:1685 ] _boost_LIBRARY_SEARCH_DIRS_DEBUG = "/usr/local/lib;NO_DEFAULT_PATH;NO_CMAKE_FIND_ROOT_PATH"
-- [ /usr/local/share/cmake-3.15/Modules/FindBoost.cmake:1869 ] Searching for FILESYSTEM_LIBRARY_RELEASE: boost_filesystem-gcc48-mt-1_60;boost_filesystem-gcc48-mt;boost_filesystem-gcc48-mt;boost_filesystem-mt-1_60;boost_filesystem-mt;boost_filesystem-mt;boost_filesystem-mt;boost_filesystem
-- [ /usr/local/share/cmake-3.15/Modules/FindBoost.cmake:473 ] Boost_LIBRARY_DIR_RELEASE = "/usr/local/lib"
-- [ /usr/local/share/cmake-3.15/Modules/FindBoost.cmake:475 ] _boost_LIBRARY_SEARCH_DIRS_RELEASE = "/usr/local/lib;NO_DEFAULT_PATH;NO_CMAKE_FIND_ROOT_PATH"
-- [ /usr/local/share/cmake-3.15/Modules/FindBoost.cmake:1924 ] Searching for FILESYSTEM_LIBRARY_DEBUG: boost_filesystem-gcc48-mt-d-1_60;boost_filesystem-gcc48-mt-d;boost_filesystem-gcc48-mt-d;boost_filesystem-mt-d-1_60;boost_filesystem-mt-d;boost_filesystem-mt-d;boost_filesystem-mt;boost_filesystem
-- [ /usr/local/share/cmake-3.15/Modules/FindBoost.cmake:473 ] Boost_LIBRARY_DIR_DEBUG = "/usr/local/lib"
-- [ /usr/local/share/cmake-3.15/Modules/FindBoost.cmake:475 ] _boost_LIBRARY_SEARCH_DIRS_DEBUG = "/usr/local/lib;NO_DEFAULT_PATH;NO_CMAKE_FIND_ROOT_PATH"
-- [ /usr/local/share/cmake-3.15/Modules/FindBoost.cmake:1869 ] Searching for IOSTREAMS_LIBRARY_RELEASE: boost_iostreams-gcc48-mt-1_60;boost_iostreams-gcc48-mt;boost_iostreams-gcc48-mt;boost_iostreams-mt-1_60;boost_iostreams-mt;boost_iostreams-mt;boost_iostreams-mt;boost_iostreams
-- [ /usr/local/share/cmake-3.15/Modules/FindBoost.cmake:473 ] Boost_LIBRARY_DIR_RELEASE = "/usr/local/lib"
-- [ /usr/local/share/cmake-3.15/Modules/FindBoost.cmake:475 ] _boost_LIBRARY_SEARCH_DIRS_RELEASE = "/usr/local/lib;NO_DEFAULT_PATH;NO_CMAKE_FIND_ROOT_PATH"
-- [ /usr/local/share/cmake-3.15/Modules/FindBoost.cmake:1924 ] Searching for IOSTREAMS_LIBRARY_DEBUG: boost_iostreams-gcc48-mt-d-1_60;boost_iostreams-gcc48-mt-d;boost_iostreams-gcc48-mt-d;boost_iostreams-mt-d-1_60;boost_iostreams-mt-d;boost_iostreams-mt-d;boost_iostreams-mt;boost_iostreams
-- [ /usr/local/share/cmake-3.15/Modules/FindBoost.cmake:473 ] Boost_LIBRARY_DIR_DEBUG = "/usr/local/lib"
-- [ /usr/local/share/cmake-3.15/Modules/FindBoost.cmake:475 ] _boost_LIBRARY_SEARCH_DIRS_DEBUG = "/usr/local/lib;NO_DEFAULT_PATH;NO_CMAKE_FIND_ROOT_PATH"
-- [ /usr/local/share/cmake-3.15/Modules/FindBoost.cmake:1869 ] Searching for LOG_LIBRARY_RELEASE: boost_log-gcc48-mt-1_60;boost_log-gcc48-mt;boost_log-gcc48-mt;boost_log-mt-1_60;boost_log-mt;boost_log-mt;boost_log-mt;boost_log
-- [ /usr/local/share/cmake-3.15/Modules/FindBoost.cmake:473 ] Boost_LIBRARY_DIR_RELEASE = "/usr/local/lib"
-- [ /usr/local/share/cmake-3.15/Modules/FindBoost.cmake:475 ] _boost_LIBRARY_SEARCH_DIRS_RELEASE = "/usr/local/lib;NO_DEFAULT_PATH;NO_CMAKE_FIND_ROOT_PATH"
-- [ /usr/local/share/cmake-3.15/Modules/FindBoost.cmake:1924 ] Searching for LOG_LIBRARY_DEBUG: boost_log-gcc48-mt-d-1_60;boost_log-gcc48-mt-d;boost_log-gcc48-mt-d;boost_log-mt-d-1_60;boost_log-mt-d;boost_log-mt-d;boost_log-mt;boost_log
-- [ /usr/local/share/cmake-3.15/Modules/FindBoost.cmake:473 ] Boost_LIBRARY_DIR_DEBUG = "/usr/local/lib"
-- [ /usr/local/share/cmake-3.15/Modules/FindBoost.cmake:475 ] _boost_LIBRARY_SEARCH_DIRS_DEBUG = "/usr/local/lib;NO_DEFAULT_PATH;NO_CMAKE_FIND_ROOT_PATH"
-- [ /usr/local/share/cmake-3.15/Modules/FindBoost.cmake:1869 ] Searching for SYSTEM_LIBRARY_RELEASE: boost_system-gcc48-mt-1_60;boost_system-gcc48-mt;boost_system-gcc48-mt;boost_system-mt-1_60;boost_system-mt;boost_system-mt;boost_system-mt;boost_system
-- [ /usr/local/share/cmake-3.15/Modules/FindBoost.cmake:473 ] Boost_LIBRARY_DIR_RELEASE = "/usr/local/lib"
-- [ /usr/local/share/cmake-3.15/Modules/FindBoost.cmake:475 ] _boost_LIBRARY_SEARCH_DIRS_RELEASE = "/usr/local/lib;NO_DEFAULT_PATH;NO_CMAKE_FIND_ROOT_PATH"
-- [ /usr/local/share/cmake-3.15/Modules/FindBoost.cmake:1924 ] Searching for SYSTEM_LIBRARY_DEBUG: boost_system-gcc48-mt-d-1_60;boost_system-gcc48-mt-d;boost_system-gcc48-mt-d;boost_system-mt-d-1_60;boost_system-mt-d;boost_system-mt-d;boost_system-mt;boost_system
-- [ /usr/local/share/cmake-3.15/Modules/FindBoost.cmake:473 ] Boost_LIBRARY_DIR_DEBUG = "/usr/local/lib"
-- [ /usr/local/share/cmake-3.15/Modules/FindBoost.cmake:475 ] _boost_LIBRARY_SEARCH_DIRS_DEBUG = "/usr/local/lib;NO_DEFAULT_PATH;NO_CMAKE_FIND_ROOT_PATH"
-- [ /usr/local/share/cmake-3.15/Modules/FindBoost.cmake:1869 ] Searching for THREAD_LIBRARY_RELEASE: boost_thread-gcc48-mt-1_60;boost_thread-gcc48-mt;boost_thread-gcc48-mt;boost_thread-mt-1_60;boost_thread-mt;boost_thread-mt;boost_thread-mt;boost_thread
-- [ /usr/local/share/cmake-3.15/Modules/FindBoost.cmake:473 ] Boost_LIBRARY_DIR_RELEASE = "/usr/local/lib"
-- [ /usr/local/share/cmake-3.15/Modules/FindBoost.cmake:475 ] _boost_LIBRARY_SEARCH_DIRS_RELEASE = "/usr/local/lib;NO_DEFAULT_PATH;NO_CMAKE_FIND_ROOT_PATH"
-- [ /usr/local/share/cmake-3.15/Modules/FindBoost.cmake:1924 ] Searching for THREAD_LIBRARY_DEBUG: boost_thread-gcc48-mt-d-1_60;boost_thread-gcc48-mt-d;boost_thread-gcc48-mt-d;boost_thread-mt-d-1_60;boost_thread-mt-d;boost_thread-mt-d;boost_thread-mt;boost_thread
-- [ /usr/local/share/cmake-3.15/Modules/FindBoost.cmake:473 ] Boost_LIBRARY_DIR_DEBUG = "/usr/local/lib"
-- [ /usr/local/share/cmake-3.15/Modules/FindBoost.cmake:475 ] _boost_LIBRARY_SEARCH_DIRS_DEBUG = "/usr/local/lib;NO_DEFAULT_PATH;NO_CMAKE_FIND_ROOT_PATH"
-- [ /usr/local/share/cmake-3.15/Modules/FindBoost.cmake:1869 ] Searching for UNIT_TEST_FRAMEWORK_LIBRARY_RELEASE: boost_unit_test_framework-gcc48-mt-1_60;boost_unit_test_framework-gcc48-mt;boost_unit_test_framework-gcc48-mt;boost_unit_test_framework-mt-1_60;boost_unit_test_framework-mt;boost_unit_test_framework-mt;boost_unit_test_framework-mt;boost_unit_test_framework
-- [ /usr/local/share/cmake-3.15/Modules/FindBoost.cmake:473 ] Boost_LIBRARY_DIR_RELEASE = "/usr/local/lib"
-- [ /usr/local/share/cmake-3.15/Modules/FindBoost.cmake:475 ] _boost_LIBRARY_SEARCH_DIRS_RELEASE = "/usr/local/lib;NO_DEFAULT_PATH;NO_CMAKE_FIND_ROOT_PATH"
-- [ /usr/local/share/cmake-3.15/Modules/FindBoost.cmake:1924 ] Searching for UNIT_TEST_FRAMEWORK_LIBRARY_DEBUG: boost_unit_test_framework-gcc48-mt-d-1_60;boost_unit_test_framework-gcc48-mt-d;boost_unit_test_framework-gcc48-mt-d;boost_unit_test_framework-mt-d-1_60;boost_unit_test_framework-mt-d;boost_unit_test_framework-mt-d;boost_unit_test_framework-mt;boost_unit_test_framework
-- [ /usr/local/share/cmake-3.15/Modules/FindBoost.cmake:473 ] Boost_LIBRARY_DIR_DEBUG = "/usr/local/lib"
-- [ /usr/local/share/cmake-3.15/Modules/FindBoost.cmake:475 ] _boost_LIBRARY_SEARCH_DIRS_DEBUG = "/usr/local/lib;NO_DEFAULT_PATH;NO_CMAKE_FIND_ROOT_PATH"
-- [ /usr/local/share/cmake-3.15/Modules/FindBoost.cmake:1869 ] Searching for REGEX_LIBRARY_RELEASE: boost_regex-gcc48-mt-1_60;boost_regex-gcc48-mt;boost_regex-gcc48-mt;boost_regex-mt-1_60;boost_regex-mt;boost_regex-mt;boost_regex-mt;boost_regex
-- [ /usr/local/share/cmake-3.15/Modules/FindBoost.cmake:473 ] Boost_LIBRARY_DIR_RELEASE = "/usr/local/lib"
-- [ /usr/local/share/cmake-3.15/Modules/FindBoost.cmake:475 ] _boost_LIBRARY_SEARCH_DIRS_RELEASE = "/usr/local/lib;NO_DEFAULT_PATH;NO_CMAKE_FIND_ROOT_PATH"
-- [ /usr/local/share/cmake-3.15/Modules/FindBoost.cmake:1924 ] Searching for REGEX_LIBRARY_DEBUG: boost_regex-gcc48-mt-d-1_60;boost_regex-gcc48-mt-d;boost_regex-gcc48-mt-d;boost_regex-mt-d-1_60;boost_regex-mt-d;boost_regex-mt-d;boost_regex-mt;boost_regex
-- [ /usr/local/share/cmake-3.15/Modules/FindBoost.cmake:473 ] Boost_LIBRARY_DIR_DEBUG = "/usr/local/lib"
-- [ /usr/local/share/cmake-3.15/Modules/FindBoost.cmake:475 ] _boost_LIBRARY_SEARCH_DIRS_DEBUG = "/usr/local/lib;NO_DEFAULT_PATH;NO_CMAKE_FIND_ROOT_PATH"
-- [ /usr/local/share/cmake-3.15/Modules/FindBoost.cmake:1869 ] Searching for DATE_TIME_LIBRARY_RELEASE: boost_date_time-gcc48-mt-1_60;boost_date_time-gcc48-mt;boost_date_time-gcc48-mt;boost_date_time-mt-1_60;boost_date_time-mt;boost_date_time-mt;boost_date_time-mt;boost_date_time
-- [ /usr/local/share/cmake-3.15/Modules/FindBoost.cmake:473 ] Boost_LIBRARY_DIR_RELEASE = "/usr/local/lib"
-- [ /usr/local/share/cmake-3.15/Modules/FindBoost.cmake:475 ] _boost_LIBRARY_SEARCH_DIRS_RELEASE = "/usr/local/lib;NO_DEFAULT_PATH;NO_CMAKE_FIND_ROOT_PATH"
-- [ /usr/local/share/cmake-3.15/Modules/FindBoost.cmake:1924 ] Searching for DATE_TIME_LIBRARY_DEBUG: boost_date_time-gcc48-mt-d-1_60;boost_date_time-gcc48-mt-d;boost_date_time-gcc48-mt-d;boost_date_time-mt-d-1_60;boost_date_time-mt-d;boost_date_time-mt-d;boost_date_time-mt;boost_date_time
-- [ /usr/local/share/cmake-3.15/Modules/FindBoost.cmake:473 ] Boost_LIBRARY_DIR_DEBUG = "/usr/local/lib"
-- [ /usr/local/share/cmake-3.15/Modules/FindBoost.cmake:475 ] _boost_LIBRARY_SEARCH_DIRS_DEBUG = "/usr/local/lib;NO_DEFAULT_PATH;NO_CMAKE_FIND_ROOT_PATH"
-- [ /usr/local/share/cmake-3.15/Modules/FindBoost.cmake:1869 ] Searching for LOG_SETUP_LIBRARY_RELEASE: boost_log_setup-gcc48-mt-1_60;boost_log_setup-gcc48-mt;boost_log_setup-gcc48-mt;boost_log_setup-mt-1_60;boost_log_setup-mt;boost_log_setup-mt;boost_log_setup-mt;boost_log_setup
-- [ /usr/local/share/cmake-3.15/Modules/FindBoost.cmake:473 ] Boost_LIBRARY_DIR_RELEASE = "/usr/local/lib"
-- [ /usr/local/share/cmake-3.15/Modules/FindBoost.cmake:475 ] _boost_LIBRARY_SEARCH_DIRS_RELEASE = "/usr/local/lib;NO_DEFAULT_PATH;NO_CMAKE_FIND_ROOT_PATH"
-- [ /usr/local/share/cmake-3.15/Modules/FindBoost.cmake:1924 ] Searching for LOG_SETUP_LIBRARY_DEBUG: boost_log_setup-gcc48-mt-d-1_60;boost_log_setup-gcc48-mt-d;boost_log_setup-gcc48-mt-d;boost_log_setup-mt-d-1_60;boost_log_setup-mt-d;boost_log_setup-mt-d;boost_log_setup-mt;boost_log_setup
-- [ /usr/local/share/cmake-3.15/Modules/FindBoost.cmake:473 ] Boost_LIBRARY_DIR_DEBUG = "/usr/local/lib"
-- [ /usr/local/share/cmake-3.15/Modules/FindBoost.cmake:475 ] _boost_LIBRARY_SEARCH_DIRS_DEBUG = "/usr/local/lib;NO_DEFAULT_PATH;NO_CMAKE_FIND_ROOT_PATH"
-- [ /usr/local/share/cmake-3.15/Modules/FindBoost.cmake:1869 ] Searching for CHRONO_LIBRARY_RELEASE: boost_chrono-gcc48-mt-1_60;boost_chrono-gcc48-mt;boost_chrono-gcc48-mt;boost_chrono-mt-1_60;boost_chrono-mt;boost_chrono-mt;boost_chrono-mt;boost_chrono
-- [ /usr/local/share/cmake-3.15/Modules/FindBoost.cmake:473 ] Boost_LIBRARY_DIR_RELEASE = "/usr/local/lib"
-- [ /usr/local/share/cmake-3.15/Modules/FindBoost.cmake:475 ] _boost_LIBRARY_SEARCH_DIRS_RELEASE = "/usr/local/lib;NO_DEFAULT_PATH;NO_CMAKE_FIND_ROOT_PATH"
-- [ /usr/local/share/cmake-3.15/Modules/FindBoost.cmake:1924 ] Searching for CHRONO_LIBRARY_DEBUG: boost_chrono-gcc48-mt-d-1_60;boost_chrono-gcc48-mt-d;boost_chrono-gcc48-mt-d;boost_chrono-mt-d-1_60;boost_chrono-mt-d;boost_chrono-mt-d;boost_chrono-mt;boost_chrono
-- [ /usr/local/share/cmake-3.15/Modules/FindBoost.cmake:473 ] Boost_LIBRARY_DIR_DEBUG = "/usr/local/lib"
-- [ /usr/local/share/cmake-3.15/Modules/FindBoost.cmake:475 ] _boost_LIBRARY_SEARCH_DIRS_DEBUG = "/usr/local/lib;NO_DEFAULT_PATH;NO_CMAKE_FIND_ROOT_PATH"
-- [ /usr/local/share/cmake-3.15/Modules/FindBoost.cmake:1869 ] Searching for ATOMIC_LIBRARY_RELEASE: boost_atomic-gcc48-mt-1_60;boost_atomic-gcc48-mt;boost_atomic-gcc48-mt;boost_atomic-mt-1_60;boost_atomic-mt;boost_atomic-mt;boost_atomic-mt;boost_atomic
-- [ /usr/local/share/cmake-3.15/Modules/FindBoost.cmake:473 ] Boost_LIBRARY_DIR_RELEASE = "/usr/local/lib"
-- [ /usr/local/share/cmake-3.15/Modules/FindBoost.cmake:475 ] _boost_LIBRARY_SEARCH_DIRS_RELEASE = "/usr/local/lib;NO_DEFAULT_PATH;NO_CMAKE_FIND_ROOT_PATH"
-- [ /usr/local/share/cmake-3.15/Modules/FindBoost.cmake:1924 ] Searching for ATOMIC_LIBRARY_DEBUG: boost_atomic-gcc48-mt-d-1_60;boost_atomic-gcc48-mt-d;boost_atomic-gcc48-mt-d;boost_atomic-mt-d-1_60;boost_atomic-mt-d;boost_atomic-mt-d;boost_atomic-mt;boost_atomic
-- [ /usr/local/share/cmake-3.15/Modules/FindBoost.cmake:473 ] Boost_LIBRARY_DIR_DEBUG = "/usr/local/lib"
-- [ /usr/local/share/cmake-3.15/Modules/FindBoost.cmake:475 ] _boost_LIBRARY_SEARCH_DIRS_DEBUG = "/usr/local/lib;NO_DEFAULT_PATH;NO_CMAKE_FIND_ROOT_PATH"
CMake Error at /usr/local/share/cmake-3.15/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find Boost (missing: filesystem log system thread
  unit_test_framework) (found suitable version "1.60.0", minimum required is
  "1.54.0")
Call Stack (most recent call first):
  /usr/local/share/cmake-3.15/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/share/cmake-3.15/Modules/FindBoost.cmake:1990 (find_package_handle_standard_args)
  CMake/deps.cmake:19 (find_package)
  CMakeLists.txt:18 (include)

-- Configuring incomplete, errors occurred!
See also "/lower_bay/home/danielle.perley/installations/dropEst/build/CMakeFiles/CMakeOutput.log".
See also "/lower_bay/home/danielle.perley/installations/dropEst/build/CMakeFiles/CMakeError.log".
`

**Comment by VPetukhov** [comment]
Hi! Are you sure that all components of boost are installed? As it states, general boost installation is found, but components "filesystem", "log", "system", "thread" and "unit_test_framework" are missing.

**Comment by epiBioCore** [comment]
Not sure. I thought I installed all the components of boost. Here's how I built and installed Boost:
[root@buddy boost_1_60_0]# ./bootstrap.sh --with-libraries=filesystem,iostreams,log,system,thread,test
[root@buddy boost_1_60_0]# ./b2 cxxflags="-std=c++11" include="/usr/local/include/" search="/usr/local/lib/" link=shared threading=multi install --prefix=/usr/local


Performing configuration checks

    - 32-bit                   : no
    - 64-bit                   : yes
    - arm                      : no
    - mips1                    : no
    - power                    : no
    - sparc                    : no
    - x86                      : yes
    - symlinks supported       : yes
    - zlib                     : yes
    - compiler-supports-visibility : yes
    - compiler-supports-ssse3  : yes
    - has_icu builds           : yes
    - lockfree boost::atomic_flag : no
    - compiler-supports-avx2   : yes

Component configuration:

    - atomic                   : not building
    - chrono                   : not building
    - container                : not building
    - context                  : not building
    - coroutine                : not building
    - coroutine2               : not building
    - date_time                : not building
    - exception                : not building
    - filesystem               : building
    - graph                    : not building
    - graph_parallel           : not building
    - iostreams                : building
    - locale                   : not building
    - log                      : building
    - math                     : not building
    - mpi                      : not building
    - program_options          : not building
    - python                   : not building
    - random                   : not building
    - regex                    : not building
    - serialization            : not building
    - signals                  : not building
    - system                   : building
    - test                     : building
    - thread                   : building
    - timer                    : not building
    - type_erasure             : not building
    - wave                     : not building

...found 23519 targets...
...updating 11955 targets...
common.mkdir /usr/local/include/boost
common.copy /usr/local/include/boost/type_index.hpp
common.copy /usr/local/include/boost/blank_fwd.hpp
common.copy /usr/local/include/boost/thread.hpp
common.copy /usr/local/include/boost/nondet_random.hpp
common.copy /usr/local/include/boost/io_fwd.hpp

(Keeps going for all 11955 targets)

common.copy /usr/local/include/boost/tr1/tr1/unordered_set
common.copy /usr/local/include/boost/tr1/tr1/limits
common.copy /usr/local/include/boost/tr1/tr1/string
common.copy /usr/local/include/boost/tr1/tr1/strstream
common.copy /usr/local/include/boost/tr1/tr1/numeric
common.copy /usr/local/include/boost/tr1/tr1/locale
...updated 11955 targets...

**Comment by VPetukhov** [comment]
Can you please try `ls -la /usr/local/lib/libboost*.so`? It should find `libboost_system.so` and the rest. And in general, to check if libboost installed, you can try `ldconfig -p | grep boost`.

**Comment by epiBioCore** [comment]
Ok. Definitely some issues with my installation of boost. Only  libboost_iostreams.so.1.60.0 file was found and the output of ldconfig  is pointing to an older version of boost that I thought was removed. Thank-you your help!

**Comment by ZHIDIHUAYUAN** [comment]
Hi, @epiBioCore 
I have the same problem with you. Please tell me how to deal with it. The command to install was:
`wget http://sourceforge.net/projects/boost/files/boost/1.60.0/boost_1_60_0.tar.gz  
tar xzf boost_1_60_0.tar.gz  
cd boost_1_60_0  
./bootstrap.sh --with-libraries=filesystem,iostreams,log,system,thread,test  
./b2 cxxflags="-std=c++11" include="$LOCAL_LIBS/include/" search="$LOCAL_LIBS/lib/" link=shared threading=multi install --prefix=$LOCAL_LIBS`

**Comment by ZHIDIHUAYUAN** [comment]
Hi, @epiBioCore
I have the same problem with you. Please tell me how to deal with it. The command to install was:
wget http://sourceforge.net/projects/boost/files/boost/1.60.0/boost_1_60_0.tar.gz 
 tar xzf boost_1_60_0.tar.gz cd boost_1_60_0. 
./bootstrap.sh --with-libraries=filesystem,iostreams,log,system,thread,test  
./b2 cxxflags="-std=c++11" include="$LOCAL_LIBS/include/" search="$LOCAL_LIBS/lib/" link=shared threading=multi install --prefix=$LOCAL_LIBS

**Comment by evanbiederstedt** [comment]
Hi @ZHIDIHUAYUAN 

Just as a heads up, there are other ways to install Boost given your operating system, e.g. https://stackoverflow.com/questions/12578499/how-to-install-boost-on-ubuntu

**Comment by ZHIDIHUAYUAN** [comment]
Hi @evanbiederstedt 
Thank you very much. I installed it successfully.

**Comment by MinjieHu** [comment]
Hi there,

I had the exactly problem. Only libboost_iostreams.so.1.60.0 file was found and the output of ldconfig is pointing to an system wide version of boost which I don't have privilege to remove. My cmake version is v.3.12.0-rc1. As I don't have root privilege, I have no ways to install with sudo apt-get. I have also try to install different boost versions, including v1..65, v1.70, v1.75, and none of them works.

Thanks ahead for any help!

**Comment by evanbiederstedt** [comment]
Yeah, this is basically a question about how to install Boost libraries. 

https://askubuntu.com/questions/2167/how-to-build-application-without-sudo-privileges

Without sudo, please try `./configure --prefix=/home/user/opt/` or (if using cmake) try `cmake -D CMAKE_INSTALL_PREFIX:PATH=/home/user/opt/ ../source/`

The tricky thing is....there's little else we can do with regards to helping debug this. This is one of the reasons containers have grown in popularity---I encourage you to try to use dropEst with Docker or Singularity.

**Comment by MinjieHu** [comment]
I follow the installation in the dropest Setup page.
```
./bootstrap.sh --with-libraries=filesystem,iostreams,log,system,thread,test
./b2 cxxflags="-std=c++11" include="$LOCAL_LIBS/include/" search="$LOCAL_LIBS/lib/" link=shared threading=multi install --prefix=$LOCAL_LIBS
```
It do install into a local directory. The weird thing is I didn't get any error messages.

**Comment by MinjieHu** [comment]
Hi @evanbiederstedt 

Thanks for the quick response. I do agree containers is a good way to go. Another issue I am currently facing is the system don't have access to the Internet except internal ones. That's why I have to install manually and It does create more difficulties.
