### ISSUE TITLE
local installation?

### ISSUE THREAD

**Issue by edroaldo** [hms-dbmi/dropEst#95]
Would somebody here please help me with the following issue:

These commands run just fine:
mkdir dropEst/build
cd dropEst/build
cmake .. && make

but when I run:

make install

$ make install
[ 11%] Built target DropTools
[ 58%] Built target Estimation
[ 61%] Built target TestTools
[ 82%] Built target TagsSearch
[ 85%] Built target droptag
[ 88%] Built target dropest
[ 91%] Built target TestEstimationMergeProbs
[ 94%] Built target filter_mixture_bam
[ 97%] Built target TestTagsSearch
[100%] Built target TestEstimation
Install the project...
-- Install configuration: ""
-- Installing: /usr/local/lib/libTagsSearch.a
CMake Error at cmake_install.cmake:41 (file):
  file INSTALL cannot copy file "/home/userX/dropEst/build/libTagsSearch.a"
  to "/usr/local/lib/libTagsSearch.a".

I could quite find a way to solve that yet. Would be possible to force a local installation?
Thank you for your time!

Thanks much!

**Comment by VPetukhov** [comment]
Hi @edroaldo ,
You just need to pass this path to cmake with `-D CMAKE_INSTALL_PREFIX` option, e.g. `cmake -D CMAKE_INSTALL_PREFIX=/home/userX/local/ . && make`. I updated [the documentation](https://dropest.readthedocs.io/en/latest/setup.html#installation) to cover this

**Comment by edroaldo** [comment]
Thanks! It is working now!
